const DATA_API="https://script.google.com/macros/s/AKfycbx3r8_KKM-jHIpPoL6dEa-IKIXZqfjxWDr3jJQF8AC2QvjL7MUrEGBuoNRkvpG9k6lnhQ/exec";
const APP_URL="https://www.appsheet.com/start/dd6cf0f7-86b7-44e6-bfbe-f3a94314ef51?platform=desktop";
const HOUSE_ORDER=["Biru","Kuning","Ungu","Merah"];
const META={Biru:{color:"#246bfd",official:"Tun Hussein Onn",short:"THO"},Kuning:{color:"#e5ad00",official:"Tun Abdul Razak",short:"TAR"},Ungu:{color:"#5b3fd0",official:"Tunku Abdul Rahman",short:"TuAR"},Merah:{color:"#df3f47",official:"Tun Mahathir",short:"TM"}};
const $=id=>document.getElementById(id);
const safe=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function loadDatabase(){try{const r=await fetch(DATA_API,{cache:"no-store",redirect:"follow"});if(!r.ok)throw Error();const d=await r.json();if(!d.years)throw Error();return d}catch{const r=await fetch("data.json",{cache:"no-store"});return r.json()}}
const emptyYear=()=>({houses:{},schedule:[],results:[]});
const participants=d=>HOUSE_ORDER.flatMap(h=>(d.houses?.[h]?.participants||[]).map(x=>({...x,house:h})));
const members=d=>HOUSE_ORDER.flatMap(h=>(d.houses?.[h]?.members||[]).map(x=>typeof x==="string"?{name:x,house:h}:({...x,house:h})));
const officialSchedule=d=>(d.schedule||[]).filter(x=>x.championshipDay&&x.date&&x.time&&x.event);
function resultGender(row){const t=(String(row.gender||"")+" "+String(row.event||"")).toLowerCase();return/perempuan|wanita|puteri/.test(t)?"Perempuan":/lelaki|putera/.test(t)?"Lelaki":""}
function leaders(d,gender){const m=new Map();(d.results||[]).filter(r=>[1,2,3].includes(Number(r.place))&&resultGender(r)===gender).forEach(r=>{const k=r.athleteId||`${r.house}|${r.athlete}`;if(!m.has(k))m.set(k,{name:r.athlete,house:r.house,gold:0,silver:0,bronze:0});const a=m.get(k);if(+r.place===1)a.gold++;if(+r.place===2)a.silver++;if(+r.place===3)a.bronze++});return[...m.values()].sort((a,b)=>b.gold-a.gold||b.silver-a.silver||b.bronze-a.bronze)}
function setupAdmin(){document.querySelectorAll("[data-admin]").forEach(b=>{if(b.dataset.ready)return;b.dataset.ready="1";b.addEventListener("click",()=>{const d=$("adminDialog");if(d)d.showModal();else window.open(APP_URL,"_blank")})});const d=$("adminDialog");if(d&&!d.dataset.ready){d.dataset.ready="1";d.querySelector(".dialog-close").onclick=()=>d.close();d.addEventListener("click",e=>{if(e.target===d)d.close()})}}
async function start(){setupAdmin();const db=await loadDatabase();const years=Object.keys(db.years||{}).sort();const params=new URLSearchParams(location.search);let year=params.get("tahun")||((years.includes("2026")&&"2026")||years[0]||"2026");const select=$("yearSelect");if(select){select.innerHTML=years.map(y=>`<option value="${safe(y)}">${safe(y)}${y==="2025"?" — Data Dummy":""}</option>`).join("");select.value=year;select.onchange=()=>{year=select.value;renderPage(db,year)}}renderPage(db,year)}
function renderPage(db,year){const d=db.years?.[year]||emptyYear();if($("heroYear"))$("heroYear").textContent=year;if($("memberCount"))$("memberCount").textContent=members(d).length;if($("participantCount"))$("participantCount").textContent=participants(d).length;if($("eventCount"))$("eventCount").textContent=officialSchedule(d).length;if($("resultCount"))$("resultCount").textContent=(d.results||[]).length;const page=document.body.dataset.page;if(page==="portal")renderHome(d);if(page==="houses")renderHouses(d,year);if(page==="students")renderStudents(d,year);if(page==="entries")renderEntries(d,year);if(page==="events")renderEvents();if(page==="schedule")renderSchedule(d,year);if(page==="medals")renderMedals(d)}
function medalData(d){return HOUSE_ORDER.map(name=>{const rr=(d.results||[]).filter(r=>r.house===name),gold=rr.filter(r=>+r.place===1).length,silver=rr.filter(r=>+r.place===2).length,bronze=rr.filter(r=>+r.place===3).length,fourth=rr.filter(r=>+r.place===4).length;return{name,gold,silver,bronze,fourth,medals:gold+silver+bronze,points:gold*7+silver*5+bronze*3+fourth}}).sort((a,b)=>b.points-a.points||b.gold-a.gold||b.silver-a.silver||b.bronze-a.bronze)}
function renderHome(d){const rows=medalData(d),has=rows.some(r=>r.gold+r.silver+r.bronze);if($("leadingHouse"))$("leadingHouse").textContent=has?rows[0].name:"Belum ada";if($("homeMedals"))$("homeMedals").innerHTML=rows.map((r,i)=>`<div class="mini-medal-row"><b>${has?i+1:"—"}</b><strong style="--house:${META[r.name].color}"><i></i>Rumah ${r.name}</strong><span>🥇 ${r.gold}</span><span>🥈 ${r.silver}</span><span>🥉 ${r.bronze}</span><b>${r.gold+r.silver+r.bronze}</b></div>`).join("");if($("homeAwards")){const cards=[["Olahragawan",leaders(d,"Lelaki")[0]],["Olahragawati",leaders(d,"Perempuan")[0]]];$("homeAwards").innerHTML=cards.map(([title,a])=>`<article class="athlete-mini"><small>${title.toUpperCase()} SEMASA</small><b>${a?safe(a.name):"Belum ditentukan"}</b><span>${a?`Rumah ${safe(a.house)} • 🥇 ${a.gold} 🥈 ${a.silver} 🥉 ${a.bronze}`:"Keputusan individu belum lengkap."}</span></article>`).join("")}}
function renderHouses(d,year){$("houseGrid").innerHTML=HOUSE_ORDER.map(name=>{const h=d.houses?.[name]||{},teachers=String(h.teacher||"").split(";").filter(Boolean);return`<article class="house-tile" style="--house:${META[name].color}"><span class="temp-label">Logo sementara</span><div class="crest"><span>${META[name].short}</span></div><small>RUMAH ${name.toUpperCase()}</small><h2>${safe(h.officialName||META[name].official)}</h2><p>Moto: ${safe(h.motto||"Belum diisi")} • Slogan: ${safe(h.slogan||"Belum diisi")}</p><div class="house-stats"><b>${teachers.length} guru</b><b>${(h.members||[]).length} ahli</b></div><a href="rumah.html?rumah=${encodeURIComponent(name)}&tahun=${year}">Buka halaman ${name} →</a></article>`}).join("")}
function renderStudents(d,year){const rows=members(d);$("studentRows").innerHTML=rows.length?rows.map(x=>`<div class="data-row"><b>${safe(x.name)}</b><span>${safe(x.class||x.kelas||x.level||"Belum diisi")}</span><span>Rumah ${safe(x.house)}</span><span class="dummy">${safe(year)}${year==="2025"?" • DUMMY":""}</span><button class="admin-link" data-admin>Edit di AppSheet</button></div>`).join(""):`<div class="empty">Belum ada murid didaftarkan untuk tahun ${safe(year)}.</div>`;setupAdmin()}
function renderEntries(d,year){const rows=participants(d);$("entryRows").innerHTML=rows.length?rows.map(x=>`<div class="data-row"><b>${safe(x.name)}</b><span>Rumah ${safe(x.house)}</span><span>${safe(x.event)}</span><span>${safe(x.category||"—")}</span><span class="dummy">${safe(year)}</span></div>`).join(""):`<div class="empty">Belum ada penyertaan untuk tahun ${safe(year)}. Daftar melalui AppSheet.</div>`}
function renderEvents(){const list=[["50 meter","Balapan • Individu","Saat • masa terendah menang"],["100 meter","Balapan • Individu","Saat • masa terendah menang"],["200 meter","Balapan • Individu","Saat • masa terendah menang"],["4 × 100 meter","Balapan • Berkumpulan","Saat • masa terendah menang"],["4 × 200 meter","Balapan • Berkumpulan","Saat • masa terendah menang"],["Lompat jauh","Padang • Individu","Meter • jarak tertinggi menang"],["Lompat tinggi","Padang • Individu","Meter • ketinggian tertinggi menang"],["Lontar peluru","Padang • Individu","Meter • jarak tertinggi menang"]];$("eventGrid").innerHTML=list.map(x=>`<article class="event-card"><small>${x[1]}</small><b>${x[0]}</b><span>Catatan wajib: ${x[2]}</span></article>`).join("")}
function renderSchedule(d,year){const rows=officialSchedule(d);$("scheduleRows").innerHTML=rows.length?rows.map(r=>`<div class="data-row"><b>${safe(r.championshipDay)}<small>${safe(r.weekday)} • ${safe(r.date)}</small></b><span>${safe(r.time)}</span><b>${safe(r.event)}</b><span>${safe(r.category)}</span><span>${safe(r.venue||"—")}</span><span>${safe(r.status||"Dijadualkan")}</span></div>`).join(""):`<div class="empty">Atur cara rasmi tiga hari belum diterbitkan untuk tahun ${safe(year)}.</div>`}
function renderMedals(d){
  const rows=medalData(d);
  const has=rows.some(x=>x.points);
  const total=rows.reduce((n,x)=>n+x.points,0);
  const max=Math.max(1,...rows.map(x=>x.points));
  $("medalRows").innerHTML=rows.map((r,i)=>`<div class="medal-row extended"><b>${has?i+1:"—"}</b><strong style="--house:${META[r.name].color}"><i></i><span>Rumah ${r.name}<small>${META[r.name].official}</small></span></strong><span>🥇 ${r.gold}</span><span>🥈 ${r.silver}</span><span>🥉 ${r.bronze}</span><span>4️⃣ ${r.fourth}</span><b>${r.medals}</b><em style="--house:${META[r.name].color}">${r.points}<small>Mata</small></em></div>`).join("");
  if($("totalPoints"))$("totalPoints").textContent=`Jumlah: ${total} Mata`;
  if($("pointsChart"))$("pointsChart").innerHTML=rows.map(r=>{const percent=total?` (${Math.round(r.points/total*100)}%)`:"";return `<div class="bar-row" style="--house:${META[r.name].color}"><div><b>Rumah ${r.name} (${META[r.name].official})</b><span>${r.points} Mata${percent}</span></div><i><b style="width:${r.points/max*100}%"></b></i></div>`}).join("");
  if($("medalBreakdown"))$("medalBreakdown").innerHTML=rows.map(r=>`<article style="--house:${META[r.name].color}"><h3><i></i>${r.name}</h3><span>🥇 Emas <b>${r.gold}</b></span><span>🥈 Perak <b>${r.silver}</b></span><span>🥉 Gangsa <b>${r.bronze}</b></span><span>4️⃣ Ke-4 <b>${r.fourth}</b></span><strong>${r.points} Mata</strong></article>`).join("");
  const cards=[["Olahragawan",leaders(d,"Lelaki")[0]],["Olahragawati",leaders(d,"Perempuan")[0]]];
  $("awardGrid").innerHTML=cards.map(([title,a])=>`<article class="award-card"><small>${title.toUpperCase()}</small><b>${a?safe(a.name):"Belum ditentukan"}</b><span>${a?`Rumah ${safe(a.house)} • 🥇 ${a.gold} 🥈 ${a.silver} 🥉 ${a.bronze}`:"Akan dikira automatik daripada keputusan individu."}</span></article>`).join("");
}
start().catch(()=>document.body.insertAdjacentHTML("afterbegin",'<div class="notice">Data tidak dapat dibaca. Sila muat semula halaman.</div>'));
