const DATA_API="https://script.google.com/macros/s/AKfycbx3r8_KKM-jHIpPoL6dEa-IKIXZqfjxWDr3jJQF8AC2QvjL7MUrEGBuoNRkvpG9k6lnhQ/exec";
const APP_URL="https://www.appsheet.com/start/dd6cf0f7-86b7-44e6-bfbe-f3a94314ef51?platform=desktop";
const HOUSE_ORDER=["Biru","Kuning","Ungu","Merah"];
const META={Biru:{color:"#246bfd",short:"B"},Kuning:{color:"#e5ad00",short:"K"},Ungu:{color:"#6d36d8",short:"U"},Merah:{color:"#df3f47",short:"M"}};
const EVENT_CATEGORY_STRUCTURE=[
  {stage:"PRASEKOLAH",code:"PRA",cohort:"Prasekolah",years:"Prasekolah",events:[{name:"50 meter",type:"Individu"},{name:"4 × 50 meter",type:"Berkumpulan"}]},
  {stage:"TAHAP 1",code:"T1-A",cohort:"Tahun 1",years:"Kategori A • Tahun 1 sahaja",events:[{name:"50 meter",type:"Individu"},{name:"80 meter",type:"Individu"},{name:"4 × 50 meter",type:"Berkumpulan"},{name:"4 × 80 meter",type:"Berkumpulan"}]},
  {stage:"TAHAP 1",code:"T1-B",cohort:"Tahun 2 & Tahun 3",years:"Kategori B • Tahun 2 dan Tahun 3 digabungkan",events:[{name:"50 meter",type:"Individu"},{name:"80 meter",type:"Individu"},{name:"4 × 50 meter",type:"Berkumpulan"},{name:"4 × 80 meter",type:"Berkumpulan"}]},
  {stage:"TAHAP 2",code:"T2-A",cohort:"Tahun 4 & Tahun 5",years:"Kategori A • Tahun 4 dan Tahun 5 digabungkan",events:[{name:"4 × 100 meter",type:"Berkumpulan"},{name:"4 × 200 meter",type:"Berkumpulan"}]},
  {stage:"TAHAP 2",code:"T2-B",cohort:"Tahun 6",years:"Kategori B • Tahun 6 sahaja",events:[{name:"4 × 100 meter",type:"Berkumpulan"},{name:"4 × 200 meter",type:"Berkumpulan"}]}
];
const $=id=>document.getElementById(id);
const safe=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function loadDatabase(){try{const r=await fetch(DATA_API,{cache:"no-store",redirect:"follow"});if(!r.ok)throw Error();const d=await r.json();if(!d.years)throw Error();return d}catch{const r=await fetch("data.json",{cache:"no-store"});return r.json()}}
const emptyYear=()=>({houses:{},schedule:[],results:[]});
const participants=d=>HOUSE_ORDER.flatMap(h=>(d.houses?.[h]?.participants||[]).map(x=>({...x,house:h})));
const members=d=>HOUSE_ORDER.flatMap(h=>(d.houses?.[h]?.members||[]).map(x=>typeof x==="string"?{name:x,house:h}:({...x,house:h})));
const houseMemberCount=h=>Number(h?.memberCount??h?.members?.length??0);
const houseParticipantCount=h=>Number(h?.participantCount??h?.participants?.length??0);
const totalMembers=d=>HOUSE_ORDER.reduce((sum,name)=>sum+houseMemberCount(d.houses?.[name]),0);
const totalParticipants=d=>HOUSE_ORDER.reduce((sum,name)=>sum+houseParticipantCount(d.houses?.[name]),0);
const officialSchedule=d=>(d.schedule||[]).filter(x=>x.championshipDay&&x.date&&x.time&&x.event);
function resultGender(row){const t=(String(row.gender||"")+" "+String(row.event||"")).toLowerCase();return/perempuan|wanita|puteri/.test(t)?"Perempuan":/lelaki|putera/.test(t)?"Lelaki":""}
function resultPoints(place){return({1:7,2:5,3:3,4:1})[Number(place)]||0}
function individualResult(row){return row.athleteId&&!/berkumpul|relay|4\s*[×x]/i.test(`${row.entryType||""} ${row.event||""}`)}
function leaders(d,gender){const m=new Map();(d.results||[]).filter(r=>[1,2,3,4].includes(Number(r.place))&&resultGender(r)===gender&&individualResult(r)).forEach(r=>{const k=r.athleteId;if(!m.has(k))m.set(k,{athleteId:k,name:r.athlete,house:r.house,gold:0,silver:0,bronze:0,fourth:0,points:0,photo:d.athletePhotos?.[k]||""});const a=m.get(k),place=+r.place;if(place===1)a.gold++;if(place===2)a.silver++;if(place===3)a.bronze++;if(place===4)a.fourth++;a.points+=resultPoints(place)});return[...m.values()].sort((a,b)=>b.points-a.points||b.gold-a.gold||b.silver-a.silver||b.bronze-a.bronze||String(a.name).localeCompare(String(b.name)))}
function setupAdmin(){document.querySelectorAll("[data-admin]").forEach(b=>{if(b.dataset.ready)return;b.dataset.ready="1";b.addEventListener("click",()=>{const d=$("adminDialog");if(d)d.showModal();else location.href="guru.html"})});const d=$("adminDialog");if(d&&!d.dataset.ready){d.dataset.ready="1";d.querySelector(".dialog-close").onclick=()=>d.close();d.addEventListener("click",e=>{if(e.target===d)d.close()})}}
function setupRefresh(){document.querySelectorAll(".sync-button").forEach(button=>{if(button.dataset.ready)return;button.dataset.ready="1";button.addEventListener("click",()=>{button.disabled=true;button.textContent="↻ Menyegerak…";const url=new URL(location.href);url.searchParams.set("segar",Date.now());location.href=url.toString()})})}
let deferredInstallPrompt=null;
function setupPWAInstall(){
  const button=$("pwaInstallButton"),dialog=$("pwaDialog"),native=$("pwaNativeInstall");if(!button||!dialog)return;
  const standalone=window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true;if(standalone){button.hidden=true;return}
  const close=dialog.querySelector(".dialog-close");close.onclick=()=>dialog.close();dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});
  button.onclick=()=>{if(deferredInstallPrompt){native.hidden=false;$("pwaInstallMessage").textContent="Pelayar ini bersedia memasang KOT 26 sebagai aplikasi."}else native.hidden=true;dialog.showModal()};
  native.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;native.hidden=true;dialog.close()};
  window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstallPrompt=event;button.classList.add("ready")});
  window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;button.hidden=true;if(dialog.open)dialog.close()});
}
async function start(){setupAdmin();setupRefresh();const db=await loadDatabase();const years=Object.keys(db.years||{}).sort();const params=new URLSearchParams(location.search);let year=params.get("tahun")||((years.includes("2026")&&"2026")||years[0]||"2026");const select=$("yearSelect");if(select){select.innerHTML=years.map(y=>`<option value="${safe(y)}">${safe(y)}${y==="2025"?" — Data Dummy":""}</option>`).join("");select.value=year;select.onchange=()=>{year=select.value;renderPage(db,year)}}renderPage(db,year)}
function renderPage(db,year){const d=db.years?.[year]||emptyYear();if($("heroYear"))$("heroYear").textContent=year;if($("memberCount"))$("memberCount").textContent=totalMembers(d);if($("participantCount"))$("participantCount").textContent=totalParticipants(d);if($("eventCount"))$("eventCount").textContent=officialSchedule(d).length;if($("resultCount"))$("resultCount").textContent=(d.results||[]).length;document.querySelectorAll("[data-current-year]").forEach(el=>el.textContent=year);const hero=document.querySelector(".dashboard-hero"),banner=String(db.settings?.bannerUrl||"");if(hero&&/^https:\/\//i.test(banner)){hero.classList.add("has-custom-banner");hero.style.setProperty("--banner-image",`url(${JSON.stringify(banner)})`)}const page=document.body.dataset.page;if(page==="portal")renderHome(d);if(page==="houses")renderHouses(d,year);if(page==="students")renderStudents(d,year);if(page==="entries")renderEntries(d,year);if(page==="events")renderEvents();if(page==="schedule")renderSchedule(d,year);if(page==="calendar")renderCalendar(d,year);if(page==="heats")renderHeats(d,year);if(page==="print")renderPrintCentre(d,year);if(page==="medals")renderMedals(d);if(page==="teacher")renderTeacherPortal(d,year);if(page==="committee")renderCommittee(d,year)}
function cleanTeacher(value){return String(value||"").replace(/^\d+\.\s*/,"").trim()}
function renderTeacherPortal(d,year){
  const total=totalMembers(d);
  if($("teacherMemberTotal"))$("teacherMemberTotal").textContent=total.toLocaleString("ms-MY");
  if($("teacherYear"))$("teacherYear").textContent=year;
  const grid=$("teacherHouseGrid");if(!grid)return;
  grid.innerHTML=HOUSE_ORDER.map((name,index)=>{const h=d.houses?.[name]||{},teachers=String(h.teacher||"").split(";").map(cleanTeacher).filter(Boolean),lead=(teachers.find(x=>/\(K\)/i.test(x))||teachers[0]||"Belum ditetapkan").replace(/\s*\(K\)\s*/i,"").trim(),count=houseMemberCount(h),meta=META[name];return `<article class="teacher-house-card" style="--house:${meta.color}"><div class="teacher-crest"><span>${meta.short}</span><small>0${index+1}</small></div><div class="teacher-house-copy"><small>PASUKAN RASMI</small><h3>Rumah ${safe(name)}</h3><p><b>${teachers.length}</b> guru <i></i> <b>${count}</b> murid</p><span>Ketua guru: ${safe(lead)}</span></div><div class="teacher-house-actions"><a href="rumah.html?rumah=${encodeURIComponent(name)}&tahun=${encodeURIComponent(year)}">Lihat profil</a><a class="manage" href="guru.html">Log masuk →</a></div></article>`}).join("")
}
const COMMITTEE_DEFAULTS=[
  [1,"Induk","Guru Besar","Penaung dan ketua pengurusan kejohanan","Yunus bin Patarai","assets/pentadbir/yunus-bin-patarai.png"],[2,"Pengurusan","Penolong Kanan Pentadbiran","Menyelaras pentadbiran dan pengurusan sekolah","Rahmatiah bt Mohd Juda","assets/pentadbir/rahmatiah-bt-mohd-juda.png"],[3,"Pengurusan","Penolong Kanan Kokurikulum","Menyelaras sukan, kokurikulum dan pelaksanaan kejohanan","Warnah bt Sira","assets/pentadbir/warnah-bt-sira.png"],[4,"Pengurusan","Penolong Kanan HEM","Menyelaras kebajikan, disiplin dan keselamatan murid","Komala bt Joseph","assets/pentadbir/komala-bt-joseph.png"],[5,"Pengurusan","Penolong Kanan Petang","Menyelaras penglibatan dan operasi sesi petang","Emran bin Selamat","assets/pentadbir/emran-bin-selamat.png"],[6,"Sekretariat","Setiausaha Sukan","Menyelaras keseluruhan perancangan dan perjalanan kejohanan","Rosidian bin Idris","assets/pentadbir/rosidian-bin-idris.png"],[7,"Sekretariat","Penolong Setiausaha Sukan","Membantu dokumentasi, jadual dan urusan teknikal"],[8,"Sekretariat","Bendahari","Mengurus kewangan, pembelian dan rekod perbelanjaan"],[9,"Sekretariat","Pengurus Pertandingan","Menyelaras acara, pegawai dan keputusan rasmi"],
  [10,"Pelaksana","Teknikal & Pengadilan","Mengurus pengadil, peraturan dan keputusan teknikal"],[11,"Pelaksana","Pendaftaran & Saringan","Mengurus peserta, nombor giliran, saringan dan lorong"],[12,"Pelaksana","Peralatan & Persiapan Tempat","Menyediakan venue, trek, padang dan peralatan pertandingan"],[13,"Pelaksana","Kepegawaian","Menyusun dan mengesahkan petugas kejohanan"],[14,"Pelaksana","Hadiah & Sijil","Mengurus pingat, hadiah, sijil dan penyampaian"],[15,"Pelaksana","Dokumentasi & Statistik","Mengurus foto, laporan, data dan statistik kejohanan"],[16,"Pelaksana","Siar Raya & Pengacaraan","Mengurus pengumuman, pengacara dan sistem audio"],[17,"Pelaksana","Keselamatan & Kecemasan","Mengurus keselamatan, disiplin dan bantuan kecemasan"],[18,"Pelaksana","Jamuan","Mengurus makanan dan minuman murid serta petugas"],[19,"Pelaksana","Buku Program & Publisiti","Menyediakan buku program, hebahan dan bahan promosi"],[20,"Pelaksana","Kawad Kaki & Perbarisan","Menyelaras perbarisan, sepanduk dan kontinjen rumah sukan"]
].map(([order,level,position,duty,name="",photo=""])=>({order,level,position,name,photo,duty}));
function orgAvatar(item){const photo=String(item.photo||"").trim();if(/^(https:\/\/|assets\/)/i.test(photo))return `<img src="${safe(photo)}" alt="Gambar ${safe(item.name||item.position)}" loading="lazy">`;const initials=String(item.name||item.position||"AJK").split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();return `<span>${safe(initials)}</span>`}
function orgCard(item,kind="unit"){return `<article class="org-card org-${kind}"><div class="org-avatar">${orgAvatar(item)}</div><div><small>${safe(item.position||"Jawatan belum diisi")}</small><h3>${safe(item.name||"Belum ditetapkan")}</h3><p>${safe(item.duty||"Bidang tugas belum diisi")}</p></div><b>${String(Number(item.order)||0).padStart(2,"0")}</b></article>`}
function renderCommittee(d,year){
  const rows=(d.committee?.length?d.committee:COMMITTEE_DEFAULTS).filter(x=>String(x.active||"YA").toUpperCase()!=="TIDAK").map(x=>({...x})).sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999));
  const take=predicate=>{const index=rows.findIndex(predicate);return index<0?null:rows.splice(index,1)[0]};
  const fallback=position=>({...COMMITTEE_DEFAULTS.find(x=>x.position===position)});
  const role=(position,matcher,legacyMatcher)=>{const exact=take(matcher),legacy=!exact&&legacyMatcher?take(x=>legacyMatcher(x)&&String(x.name||"").trim()):null;return{...fallback(position),...(exact||legacy||{}),position}};
  const top=role("Guru Besar",x=>/guru besar/i.test(x.position||""),x=>/penaung|penasihat|^pengerusi$/i.test(x.position||""));
  const deputies=[
    role("Penolong Kanan Pentadbiran",x=>/penolong kanan.*pentadbiran|\bpk\s*pentadbiran/i.test(x.position||"")),
    role("Penolong Kanan Kokurikulum",x=>/penolong kanan.*ko?kurikulum|\bpk\s*ko?kurikulum/i.test(x.position||"")),
    role("Penolong Kanan HEM",x=>/penolong kanan.*hem|hal ehwal murid|\bpk\s*hem/i.test(x.position||"")),
    role("Penolong Kanan Petang",x=>/penolong kanan.*petang|penyelia petang|\bpk\s*petang/i.test(x.position||""))
  ];
  const secretary=role("Setiausaha Sukan",x=>/setiausaha sukan/i.test(x.position||"")&&!/penolong/i.test(x.position||""),x=>/^setiausaha$/i.test(x.position||""));
  const secretariat=[
    role("Penolong Setiausaha Sukan",x=>/penolong setiausaha/i.test(x.position||"")),
    role("Bendahari",x=>/bendahari/i.test(x.position||"")),
    role("Pengurus Pertandingan",x=>/pengurus pertandingan/i.test(x.position||""))
  ];
  const unitDefaults=COMMITTEE_DEFAULTS.filter(x=>x.level==="Pelaksana");
  const aliases={"Peralatan & Persiapan Tempat":/peralatan/i,"Dokumentasi & Statistik":/dokumentasi|statistik/i,"Siar Raya & Pengacaraan":/siar raya|pengacara/i,"Buku Program & Publisiti":/buku program|publisiti/i,"Kawad Kaki & Perbarisan":/kawad|perbarisan/i};
  const units=unitDefaults.map(base=>{const pattern=aliases[base.position]||new RegExp(base.position.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"),match=take(x=>pattern.test(x.position||""));return{...base,...(match||{}),position:base.position}});
  rows.filter(x=>String(x.level||"").toLowerCase()==="pelaksana").forEach(x=>units.push(x));
  top.order=1;deputies.forEach((x,i)=>x.order=i+2);secretary.order=6;secretariat.forEach((x,i)=>x.order=i+7);units.forEach((x,i)=>x.order=i+10);
  if($("committeeCount"))$("committeeCount").textContent=[top,...deputies,secretary,...secretariat,...units].filter(Boolean).length;if($("committeeYear"))$("committeeYear").textContent=year;
  if($("orgChart"))$("orgChart").innerHTML=`<section class="org-tier org-tier-top"><span class="tier-label">PUNCAK PENGURUSAN</span>${top?orgCard(top,"top"):""}</section><div class="org-connector"></div><section class="org-tier org-tier-deputies"><span class="tier-label">BARISAN PENOLONG KANAN</span><div>${deputies.map(x=>orgCard(x,"deputy")).join("")||'<div class="org-empty">Jawatan Penolong Kanan belum dilengkapkan.</div>'}</div></section><div class="org-connector"></div><section class="org-tier org-tier-secretary"><span class="tier-label">PENYELARAS SUKAN</span>${secretary?orgCard(secretary,"secretary"):'<div class="org-empty">Setiausaha Sukan belum ditetapkan.</div>'}</section><div class="org-connector org-connector-branch"></div><section class="org-tier org-tier-secretariat"><span class="tier-label">URUS SETIA KEJOHANAN</span><div>${secretariat.map(x=>orgCard(x,"secretariat")).join("")||'<div class="org-empty">Urus setia belum dilengkapkan.</div>'}</div></section><div class="org-connector"></div><section class="org-tier org-tier-units"><span class="tier-label">JAWATANKUASA PELAKSANA</span><div>${units.map(x=>orgCard(x,"unit")).join("")}</div></section>`;
}
function medalData(d){return HOUSE_ORDER.map(name=>{const rr=(d.results||[]).filter(r=>r.house===name),gold=rr.filter(r=>+r.place===1).length,silver=rr.filter(r=>+r.place===2).length,bronze=rr.filter(r=>+r.place===3).length,fourth=rr.filter(r=>+r.place===4).length;return{name,gold,silver,bronze,fourth,medals:gold+silver+bronze,points:gold*7+silver*5+bronze*3+fourth}}).sort((a,b)=>b.points-a.points||b.gold-a.gold||b.silver-a.silver||b.bronze-a.bronze)}
function athletePortrait(a,title){return a?.photo?`<img src="${safe(a.photo)}" alt="Gambar ${safe(a.name)}" loading="lazy">`:`<span aria-hidden="true">${title==="Olahragawan"?"🏃":"🏃‍♀️"}</span>`}
function renderHome(d){const rows=medalData(d),has=rows.some(r=>r.gold+r.silver+r.bronze);if($("leadingHouse"))$("leadingHouse").textContent=has?rows[0].name:"Belum ada";if($("homeMedals"))$("homeMedals").innerHTML=rows.map((r,i)=>`<div class="mini-medal-row"><b>${has?i+1:"—"}</b><strong style="--house:${META[r.name].color}"><i></i>Rumah ${r.name}</strong><span>🥇 ${r.gold}</span><span>🥈 ${r.silver}</span><span>🥉 ${r.bronze}</span><b>${r.gold+r.silver+r.bronze}</b></div>`).join("");if($("homeAwards")){const cards=[["Olahragawan",leaders(d,"Lelaki")[0]],["Olahragawati",leaders(d,"Perempuan")[0]]];$("homeAwards").innerHTML=cards.map(([title,a])=>`<article class="athlete-mini athlete-feature"><div class="athlete-portrait">${athletePortrait(a,title)}</div><div><small>${title.toUpperCase()} SEMASA</small><b>${a?safe(a.name):"Belum ditentukan"}</b><span>${a?`Rumah ${safe(a.house)} • 🥇 ${a.gold} • ${a.points} mata`:"Keputusan individu belum lengkap."}</span></div></article>`).join("")}}
function houseEmblem(name,logo){return logo?`<div class="house-emblem has-logo"><img src="${safe(logo)}" alt="Logo Rumah ${safe(name)}"></div>`:`<div class="house-emblem fallback-emblem" aria-label="Logo sementara Rumah ${safe(name)}"><span>${META[name].short}</span><small>SKRG</small></div>`}
function renderHouses(d,year){$("houseGrid").innerHTML=HOUSE_ORDER.map((name,index)=>{const h=d.houses?.[name]||{},teachers=String(h.teacher||"").split(";").map(x=>x.trim()).filter(Boolean);return`<article class="house-card-new" style="--house:${META[name].color}"><div class="house-card-top"><span>0${index+1}</span><b>RUMAH ${safe(name).toUpperCase()}</b></div><div class="house-visual">${houseEmblem(name,h.logo)}<div><small>PASUKAN RASMI SK RANGGU</small><h2>Rumah ${safe(name)}</h2><p>${safe(h.motto||"Moto belum diisi")}</p></div></div><blockquote>“${safe(h.slogan||"Slogan rumah akan dipaparkan di sini") }”</blockquote><div class="house-stats"><span><b>${teachers.length}</b><small>Guru</small></span><span><b>${houseMemberCount(h)}</b><small>Ahli</small></span><span><b>${Number(h.participantCount||0)}</b><small>Penyertaan</small></span></div><a href="rumah.html?rumah=${encodeURIComponent(name)}&tahun=${year}"><span>Lihat profil pasukan</span><b>→</b></a></article>`}).join("")}
function renderStudents(d,year){$("studentRows").innerHTML=`<div class="empty protected-data"><b>🔐 Senarai nama murid dilindungi</b><span>${totalMembers(d)} rekod bagi tahun ${safe(year)}. Log masuk sebagai guru untuk melihat ahli rumah sukan sendiri.</span><a class="button" href="guru.html">Log masuk Portal Guru →</a></div>`}
function renderEntries(d,year){$("entryRows").innerHTML=`<div class="empty protected-data"><b>🔐 Maklumat penyertaan dilindungi</b><span>${totalParticipants(d)} penyertaan bagi tahun ${safe(year)}. Log masuk sebagai guru untuk pengurusan rumah sendiri.</span><a class="button" href="guru.html">Log masuk Portal Guru →</a></div>`}
function renderEvents(){const grid=$("eventGrid");if(!grid)return;grid.innerHTML=EVENT_CATEGORY_STRUCTURE.map(group=>`<section class="event-group"><header><div><small>${safe(group.stage)} • ${safe(group.code)}</small><h2>${safe(group.cohort)}</h2><p>${safe(group.years)}</p></div><b>${group.events.length*2}<span>pilihan acara</span></b></header><div class="event-options">${group.events.map(event=>`<article class="event-card"><small>Balapan • ${safe(event.type)}</small><b>${safe(event.name)}</b><div><span>♂ Lelaki</span><span>♀ Perempuan</span></div><em>Catatan wajib: saat • masa terendah menang</em></article>`).join("")}</div></section>`).join("")}
function renderSchedule(d,year){const rows=officialSchedule(d);$("scheduleRows").innerHTML=rows.length?rows.map(r=>`<div class="data-row"><b>${safe(r.championshipDay)}<small>${safe(r.weekday)} • ${safe(r.date)}</small></b><span>${safe(r.time)}</span><b>${safe(r.event)}</b><span>${safe(r.category)}</span><span>${safe(r.venue||"—")}</span><span>${safe(r.status||"Dijadualkan")}</span></div>`).join(""):`<div class="empty">Atur cara rasmi tiga hari belum diterbitkan untuk tahun ${safe(year)}.</div>`}
function renderCalendar(d,year){
  const rows=officialSchedule(d),grid=$("calendarGrid"),status=$("calendarStatus");if(!grid)return;
  if(!rows.length){
    if(status)status.innerHTML=`<b>Tarikh kejohanan ${safe(year)} belum disahkan</b><span>Kalendar akan dijana automatik selepas Hari Kejohanan, tarikh dan masa dilengkapkan oleh Admin Sistem.</span>`;
    grid.innerHTML=`<article class="calendar-empty"><span>📅</span><div><h2>Belum ada takwim rasmi</h2><p>Tiada tarikh contoh dipaparkan. Senarai acara sudah tersedia dan boleh diurus melalui Portal Guru atau AppSheet sementara menunggu tarikh rasmi.</p><a href="acara.html">Lihat senarai acara</a></div></article>`;return;
  }
  const groups=new Map();rows.forEach(row=>{const key=[row.championshipDay,row.weekday,row.date].join("|");if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)});
  if(status)status.innerHTML=`<b>${groups.size} hari kejohanan diterbitkan</b><span>${rows.length} slot rasmi untuk tahun ${safe(year)}.</span>`;
  grid.innerHTML=[...groups.entries()].map(([key,items],index)=>{const [day,weekday,date]=key.split("|");return `<article class="calendar-day"><header><span>${String(index+1).padStart(2,"0")}</span><div><small>${safe(day)}</small><h2>${safe(weekday||"Hari kejohanan")}</h2><p>${safe(date)}</p></div><b>${items.length}<small>slot</small></b></header><div>${items.map(item=>`<section><time>${safe(item.time)}</time><p><b>${safe(item.event)}</b><span>${safe(item.category)} • ${safe(item.venue||"Tempat belum ditetapkan")}</span></p><em>${safe(item.status||"Dijadualkan")}</em></section>`).join("")}</div></article>`}).join("");
}
function renderHeats(d,year){
  const events=(d.events||[]).filter(e=>String(e.discipline||"").toLowerCase()==="balapan"),select=$("heatEventSelect"),stage=$("heatStage"),count=$("heatEventCount");if(!select||!stage)return;
  if(count)count.textContent=events.length;
  select.innerHTML=events.length?events.map((e,i)=>`<option value="${safe(e.id||String(i))}">${safe(e.name)}</option>`).join(""):'<option>Tiada acara balapan</option>';
  const draw=()=>{const event=events.find((e,i)=>(e.id||String(i))===select.value)||events[0];if(!event){stage.innerHTML='<div class="empty">Belum ada acara balapan untuk dijana.</div>';return}const published=(d.schedule||[]).find(x=>[event.id,event.name].some(key=>String(x.event||"").toLowerCase()===String(key||"").toLowerCase())&&x.date&&x.time),entries=(d.publishedEntries||[]).filter(x=>String(x.eventId||"")===String(event.id||"")||String(x.event||"").toLowerCase()===String(event.name||"").toLowerCase());stage.innerHTML=`<article class="heat-card"><header><div><small>${safe(event.stage)} • ${safe(event.categoryCode)} • ${safe(event.gender)}</small><h2>${safe(event.name)}</h2><p>${safe(event.entryType)} • Tahun ${safe(year)}</p></div><span>${published?`${safe(published.date)}<b>${safe(published.time||"")}</b>`:"BELUM DIJADUALKAN"}</span></header><div class="lane-grid">${HOUSE_ORDER.map((house,index)=>{const athletes=entries.filter(x=>x.house===house);return`<section style="--house:${META[house].color}"><b>${athletes[0]?.lane||index+1}</b><span><i></i>Rumah ${house}</span><em>${published?(athletes.length?athletes.map(x=>safe(x.name)).join(" • "):"Belum didaftarkan"):"Peserta dilindungi"}</em><a href="${published?"aturcara.html":"guru.html"}">${published?"Lihat jadual":"Urus melalui Portal Guru"}</a></section>`}).join("")}</div><footer><span>🏁 ${published?"Senarai peserta rasmi":"Lorong sementara mengikut empat rumah sukan"}</span><b>${published?"Dipaparkan selepas jadual disahkan":"Janaan rasmi selepas penyertaan disahkan"}</b></footer></article>`};select.onchange=draw;draw();
}
function renderPrintCentre(d,year){
  const schedule=officialSchedule(d),results=d.results||[],medals=medalData(d),root=$("printPreview");if(!root)return;
  if($("printScheduleCount"))$("printScheduleCount").textContent=schedule.length;if($("printResultCount"))$("printResultCount").textContent=results.length;
  root.innerHTML=`<section class="print-sheet"><header><div class="print-logos"><img src="assets/kpm.png" alt="Logo KPM"><img src="assets/skrg.jpeg" alt="Logo SK Ranggu"></div><div><small>SEKOLAH KEBANGSAAN RANGGU TAWAU</small><h2>Ringkasan Kejohanan Olahraga ${safe(year)}</h2><p>Peti Surat 842, 91008 Tawau, Sabah</p></div></header><div class="print-summary"><article><b>${totalMembers(d)}</b><span>Murid berdaftar</span></article><article><b>${totalParticipants(d)}</b><span>Penyertaan</span></article><article><b>${schedule.length}</b><span>Slot rasmi</span></article><article><b>${results.length}</b><span>Keputusan</span></article></div><h3>Kedudukan rumah sukan</h3><div class="print-ranking">${medals.map((row,index)=>`<section><b>${index+1}</b><span style="--house:${META[row.name].color}"><i></i>Rumah ${row.name}</span><em>🥇 ${row.gold} &nbsp; 🥈 ${row.silver} &nbsp; 🥉 ${row.bronze}</em><strong>${row.points} mata</strong></section>`).join("")}</div><footer>Dokumen dijana daripada pangkalan data rasmi SK Ranggu • <span data-current-year>${safe(year)}</span></footer></section>`;
  document.querySelectorAll("[data-print-page]").forEach(button=>button.onclick=()=>window.print());
}
function renderMedals(d){
  const rows=medalData(d);
  const has=rows.some(x=>x.points);
  const total=rows.reduce((n,x)=>n+x.points,0);
  const max=Math.max(1,...rows.map(x=>x.points));
  $("medalRows").innerHTML=rows.map((r,i)=>`<div class="medal-row extended"><b>${has?i+1:"—"}</b><strong style="--house:${META[r.name].color}"><i></i><span>Rumah ${r.name}<small>Pasukan ${r.name}</small></span></strong><span>🥇 ${r.gold}</span><span>🥈 ${r.silver}</span><span>🥉 ${r.bronze}</span><span>4️⃣ ${r.fourth}</span><b>${r.medals}</b><em style="--house:${META[r.name].color}">${r.points}<small>Mata</small></em></div>`).join("");
  if($("totalPoints"))$("totalPoints").textContent=`Jumlah: ${total} Mata`;
  if($("pointsChart"))$("pointsChart").innerHTML=rows.map(r=>{const percent=total?` (${Math.round(r.points/total*100)}%)`:"";return `<div class="bar-row" style="--house:${META[r.name].color}"><div><b>Rumah ${r.name}</b><span>${r.points} Mata${percent}</span></div><i><b style="width:${r.points/max*100}%"></b></i></div>`}).join("");
  if($("medalBreakdown"))$("medalBreakdown").innerHTML=rows.map(r=>`<article style="--house:${META[r.name].color}"><h3><i></i>${r.name}</h3><span>🥇 Emas <b>${r.gold}</b></span><span>🥈 Perak <b>${r.silver}</b></span><span>🥉 Gangsa <b>${r.bronze}</b></span><span>4️⃣ Ke-4 <b>${r.fourth}</b></span><strong>${r.points} Mata</strong></article>`).join("");
  const cards=[["Olahragawan",leaders(d,"Lelaki")[0]],["Olahragawati",leaders(d,"Perempuan")[0]]];
  $("awardGrid").innerHTML=cards.map(([title,a])=>`<article class="award-card award-feature"><div class="award-photo">${athletePortrait(a,title)}</div><div><small>${title.toUpperCase()} SEMASA</small><b>${a?safe(a.name):"Belum ditentukan"}</b><span>${a?`Rumah ${safe(a.house)} • 🥇 ${a.gold} 🥈 ${a.silver} 🥉 ${a.bronze} • ${a.points} mata`:"Akan dikira automatik daripada keputusan individu."}</span></div></article>`).join("");
  if($("eventStatistics")){const groups=new Map();(d.results||[]).forEach(row=>{const key=row.eventId||row.event;if(!groups.has(key))groups.set(key,{event:row.event,category:row.cohort||row.category||"",gender:row.eventGender||resultGender(row),rows:[]});groups.get(key).rows.push(row)});$("eventStatistics").innerHTML=groups.size?[...groups.values()].sort((a,b)=>String(a.event).localeCompare(String(b.event))).map(group=>{const winner=group.rows.find(row=>Number(row.place)===1)||group.rows.slice().sort((a,b)=>Number(a.place)-Number(b.place))[0]||{};return `<article><div><small>${safe(group.category)} • ${safe(group.gender)}</small><b>${safe(group.event)}</b><span>${group.rows.length} catatan rasmi</span></div><strong>🏆 ${safe(winner.athlete||`Pasukan Rumah ${winner.house||"—"}`)}</strong><em>${safe(winner.mark||"Belum lengkap")}</em></article>`}).join(""):'<div class="secure-empty">Belum ada statistik keputusan untuk dipaparkan.</div>'}
}
setupPWAInstall();
import("./navigation.js?v=20261005judge3").catch(()=>{});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
start().catch(()=>document.body.insertAdjacentHTML("afterbegin",'<div class="notice">Data tidak dapat dibaca. Sila muat semula halaman.</div>'));
