const AUTH_API="https://script.google.com/macros/s/AKfycbx3r8_KKM-jHIpPoL6dEa-IKIXZqfjxWDr3jJQF8AC2QvjL7MUrEGBuoNRkvpG9k6lnhQ/exec";
const SESSION_KEY="skrg_teacher_session";
const HOUSE_COLORS={Biru:"#246bfd",Kuning:"#e5ad00",Ungu:"#6b3de0",Merah:"#e5484d"};
const $=id=>document.getElementById(id);
const safe=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let session=null,workspaceData=null,adminUsers=[],compressedPhoto="",compressedHouseLogo="",compressedHouseMedia="",currentHouseMediaSlot="";

async function api(payload){
  const response=await fetch(AUTH_API,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams(payload),redirect:"follow",cache:"no-store"});
  if(!response.ok)throw Error("Pelayan data tidak dapat dihubungi.");
  const data=await response.json();if(data.error)throw Error(data.message||"Permintaan tidak berjaya.");return data;
}
function message(target,text,type="error"){target.textContent=text;target.className=`form-message ${type}`}
function clearMessage(target){target.textContent="";target.className="form-message"}
function initials(name){return String(name||"Guru").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function normalizedIc(){return $("teacherIc").value.replace(/\D/g,"")}
function isAdmin(){return session?.user?.isSystemAdmin===true}
function currentHouse(){return isAdmin()?$("workspaceHouseSelect").value:session?.user?.house||""}
function currentYear(){return $("workspaceYear").value}
function setBusy(button,busy,label){button.disabled=busy;button.dataset.label=button.dataset.label||button.textContent;button.textContent=busy?label:button.dataset.label}

async function previewTeacher(){
  const ic=normalizedIc(),preview=$("teacherPreview");preview.hidden=true;clearMessage($("loginMessage"));if(ic.length!==12)return;
  try{const result=await api({action:"lookupTeacher",ic});$("teacherPreviewName").textContent=result.name;$("teacherPreviewHouse").textContent=result.house?`Rumah ${result.house}`:"Akaun guru";preview.hidden=false}catch(error){message($("loginMessage"),error.message)}
}
async function login(event){
  event.preventDefault();const button=event.submitter;clearMessage($("loginMessage"));setBusy(button,true,"Menyemak…");
  try{const result=await api({action:"login",ic:normalizedIc(),password:$("teacherPassword").value});session={token:result.token,user:result.user,mustChange:Boolean(result.mustChange)};localStorage.setItem(SESSION_KEY,JSON.stringify(session));sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));if(result.mustChange){$("currentPassword").value=$("teacherPassword").value;$("changePasswordDialog").showModal();return}await openWorkspace()}catch(error){message($("loginMessage"),error.message)}finally{setBusy(button,false)}
}
async function adminLogin(event){
  event.preventDefault();const button=event.submitter;clearMessage($("adminAccessMessage"));setBusy(button,true,"Menyemak…");
  try{const result=await api({action:"adminLogin",code:$("adminAccessCode").value});session={token:result.token,user:result.user,mustChange:false};localStorage.setItem(SESSION_KEY,JSON.stringify(session));sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));$("adminAccessDialog").close();await openWorkspace()}catch(error){message($("adminAccessMessage"),error.message)}finally{setBusy(button,false)}
}
async function changePassword(event){
  event.preventDefault();clearMessage($("passwordMessage"));const button=event.submitter;if($("newPassword").value!==$("confirmPassword").value){message($("passwordMessage"),"Ulangan kata laluan baharu tidak sama.");return}
  setBusy(button,true,"Menyimpan…");try{await api({action:"changePassword",token:session.token,currentPassword:$("currentPassword").value,newPassword:$("newPassword").value});session.mustChange=false;localStorage.setItem(SESSION_KEY,JSON.stringify(session));sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));message($("passwordMessage"),"Kata laluan berjaya disimpan.","success");setTimeout(async()=>{$("changePasswordDialog").close();await openWorkspace()},650)}catch(error){message($("passwordMessage"),error.message)}finally{setBusy(button,false)}
}
async function openWorkspace(){
  $("loginCard").hidden=true;$("teacherWorkspace").hidden=false;const user=session.user;$("workspaceName").textContent=user.name||"Guru SK Ranggu";$("workspaceIdentity").textContent=isAdmin()?"Akses khas • Admin Sistem":`${user.id} • ${user.house?`Rumah ${user.house}`:"Akaun guru"}`;$("workspaceInitials").textContent=initials(user.name);$("workspaceRole").textContent=user.role||"Guru";
  if(isAdmin()){$("adminHouseField").hidden=false;document.querySelectorAll("[data-admin-only],[data-admin-action]").forEach(x=>x.hidden=false)}else{$("workspaceHouseSelect").value=user.house}
  await loadWorkspace();$("teacherWorkspace").scrollIntoView({behavior:"smooth",block:"start"});
}
async function loadWorkspace(){
  const house=currentHouse();try{workspaceData=await api({action:"teacherData",token:session.token,year:currentYear(),house});renderWorkspace()}catch(error){if(/sesi/i.test(error.message)){localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY);location.reload();return}$("pupilRows").innerHTML=`<div class="secure-empty">${safe(error.message)}</div>`}
}
function renderWorkspace(){
  const house=workspaceData.house||currentHouse(),profile=workspaceData.profile||{},color=HOUSE_COLORS[house]||"#0b4da2";$("workspaceHouse").style.setProperty("--house",color);$("houseTitle").textContent=house?`Rumah ${house}`:"Paparan Admin Sistem";$("houseMotto").textContent=profile.motto||"Maklumat rasmi rumah sukan";$("workspacePupilCount").textContent=(workspaceData.pupils||[]).length;$("workspaceEntryCount").textContent=(workspaceData.entries||[]).length;
  $("workspaceResultCount").textContent=(workspaceData.officialResults||[]).length;$("resultsTab").hidden=!workspaceData.canJudge;
  adminUsers=workspaceData.users||[];renderPupils();renderEntries();renderResults();renderProfile();renderUsers();renderJudgeAccess();renderAudit();$("bannerUrl").value=workspaceData.settings?.bannerUrl||"";$("tickerText").value=workspaceData.settings?.tickerText||"";$("tickerActive").value=workspaceData.settings?.tickerActive?"YA":"TIDAK";
}
function renderPupils(){
  const query=$("pupilSearch").value.trim().toLowerCase(),rows=(workspaceData?.pupils||[]).filter(row=>!query||`${row.name} ${row.class}`.toLowerCase().includes(query));
  $("pupilRows").innerHTML=rows.length?`<div class="secure-row pupil-row secure-head"><span>ID</span><span>Nama murid</span><span>Kelas</span><span>Jantina</span><span>Tindakan</span></div>${rows.map(row=>`<div class="secure-row pupil-row"><span>${safe(row.id||"—")}</span><b>${safe(row.name)}</b><span>${safe(row.class||"—")}</span><span>${safe(row.gender||"—")}</span><button class="row-action" data-edit-pupil="${safe(row.id)}">Edit</button></div>`).join("")}`:'<div class="secure-empty">Tiada rekod murid dijumpai.</div>';
  document.querySelectorAll("[data-edit-pupil]").forEach(button=>button.onclick=()=>openPupil(button.dataset.editPupil));
}
function renderEntries(){
  const rows=workspaceData?.entries||[],admin=isAdmin();$("entryRows").innerHTML=rows.length?`<div class="secure-row entry manage-entry secure-head"><span>Nama murid</span><span>Acara</span><span>Kategori</span><span>Jenis</span><span>${admin?"Tindakan Admin Sistem":"Status"}</span></div>${rows.map(row=>`<div class="secure-row entry manage-entry"><b>${safe(row.name)}</b><span>${safe(row.event)}</span><span>${safe(row.category||"—")}</span><span>${safe(row.type||"—")}</span>${admin?`<button class="row-action danger" data-delete-entry="${safe(row.id)}" data-athlete="${safe(row.name)}" data-event="${safe(row.event)}">Batalkan</button>`:'<span class="entry-sent">✓ Dihantar</span>'}</div>`).join("")}`:'<div class="secure-empty">Belum ada penyertaan direkodkan untuk tahun ini.</div>';
  document.querySelectorAll("[data-delete-entry]").forEach(button=>button.onclick=()=>openEntryCancellation(button.dataset.deleteEntry,button.dataset.athlete,button.dataset.event));
}
function eventKind(event){return/berkumpul|relay|4\s*[×x]/i.test(`${event?.type||""} ${event?.name||""}`)?"Berkumpulan":"Individu"}
function resultMode(event){return/lompat|lontar|baling|rejam|padang/i.test(`${event?.discipline||""} ${event?.name||""} ${event?.note||""}`)?"higher":"lower"}
function pointsFor(place){return({1:7,2:5,3:3,4:1})[Number(place)]||0}
function renderResults(){
  if(!workspaceData?.canJudge)return;
  const events=workspaceData.events||[],filter=$("resultEventFilter"),selected=filter.value;
  filter.innerHTML='<option value="">Semua acara</option>'+events.map(e=>`<option value="${safe(e.id)}">${safe(e.name)} • ${safe(e.cohort)} • ${safe(e.gender)}</option>`).join("");filter.value=selected;
  const rows=(workspaceData.officialResults||[]).filter(row=>!filter.value||row.eventId===filter.value).sort((a,b)=>String(a.event).localeCompare(String(b.event))||Number(a.place)-Number(b.place));
  const head='<div class="secure-row result-row secure-head"><span>Ked.</span><span>Acara / peserta</span><span>Rumah</span><span>Catatan</span><span>Mata</span><span>Petugas</span><span>Tindakan</span></div>';
  $("resultRows").innerHTML=rows.length?head+rows.map(row=>`<div class="secure-row result-row"><b class="place-badge place-${safe(row.place)}">${safe(row.place||"—")}</b><span><strong>${safe(row.event)}</strong><small>${safe(row.athlete||`Pasukan Rumah ${row.house}`)} • ${safe(row.category)}</small></span><span>${safe(row.house)}</span><b>${safe(row.mark||`${row.value} ${row.unit}`)}</b><em>${pointsFor(row.place)} mata</em><small>${safe(row.recordedBy||"—")}</small><button class="row-action danger" data-delete-result="${safe(row.id)}">Padam</button></div>`).join(""):'<div class="secure-empty">Belum ada keputusan rasmi direkodkan.</div>';
  const eventsDone=new Set(rows.map(r=>r.eventId));$("resultEventSummary").textContent=rows.length?`${rows.length} catatan • ${eventsDone.size} acara • kedudukan dan mata dikira automatik`:'Belum ada keputusan rasmi.';
  document.querySelectorAll("[data-delete-result]").forEach(button=>button.onclick=()=>deleteResult(button.dataset.deleteResult));renderJudgeAwards();
}
function renderJudgeAwards(){
  const leaders=workspaceData?.awardLeaders||{},cards=[["Olahragawan",leaders.Lelaki,"🏃"],["Olahragawati",leaders.Perempuan,"🏃‍♀️"]];
  $("judgeAwardCards").innerHTML=cards.map(([title,a,icon])=>`<article><div class="judge-award-avatar">${icon}</div><div><small>${title.toUpperCase()} SEMASA</small><b>${a?safe(a.name):"Belum ditentukan"}</b><span>${a?`Rumah ${safe(a.house)} • 🥇 ${a.gold} • ${a.points} mata`:"Keputusan individu belum mencukupi."}</span></div>${a?`<button class="row-action" data-photo-athlete="${safe(a.athleteId)}" data-photo-name="${safe(a.name)}">Muat naik gambar</button>`:""}</article>`).join("");
  document.querySelectorAll("[data-photo-athlete]").forEach(button=>button.onclick=()=>openPhoto(button.dataset.photoAthlete,button.dataset.photoName));
}
function openResult(){
  const events=workspaceData?.events||[];$("resultEvent").innerHTML='<option value="">Pilih acara</option>'+events.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.cohort)} • ${safe(event.gender)}</option>`).join("");$("resultContestant").innerHTML='<option value="">Pilih acara dahulu</option>';$("resultValue").value="";clearMessage($("resultMessage"));$("resultDialog").showModal();
}
function updateResultContestants(){
  const event=(workspaceData?.events||[]).find(row=>row.id===$("resultEvent").value),entries=(workspaceData?.judgeEntries||[]).filter(row=>row.eventId===event?.id),group=eventKind(event)==="Berkumpulan";
  const contestants=group?[...new Set(entries.map(row=>row.house))].map(house=>({value:house,label:`Pasukan Rumah ${house}`})):entries.map(row=>({value:row.pupilId,label:`${row.name} • Rumah ${row.house}`}));
  $("resultContestant").innerHTML='<option value="">Pilih peserta / pasukan</option>'+contestants.map(row=>`<option value="${safe(row.value)}">${safe(row.label)}</option>`).join("");
  const mode=resultMode(event),unit=mode==="higher"?"meter":"saat";$("resultUnit").value=unit;$("resultGuidance").textContent=event?(mode==="higher"?"Ukuran tertinggi menentukan pemenang. Gunakan meter atau sentimeter.":"Masa terendah menentukan pemenang. Masukkan jumlah saat, contohnya 12.45."):"Pilih acara untuk melihat kaedah pengiraan.";
}
async function saveResult(event){event.preventDefault();const button=event.submitter,eventInfo=(workspaceData?.events||[]).find(row=>row.id===$("resultEvent").value),group=eventKind(eventInfo)==="Berkumpulan";clearMessage($("resultMessage"));setBusy(button,true,"Mengira…");try{const result=await api({action:"saveResult",token:session.token,year:currentYear(),eventId:$("resultEvent").value,athleteId:group?"":$("resultContestant").value,house:group?$("resultContestant").value:"",value:$("resultValue").value,unit:$("resultUnit").value});message($("resultMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("resultDialog").close(),650)}catch(error){message($("resultMessage"),error.message)}finally{setBusy(button,false)}}
async function deleteResult(id){if(!confirm("Padam keputusan ini dan kira semula kedudukan?"))return;try{await api({action:"deleteResult",token:session.token,id});await loadWorkspace()}catch(error){alert(error.message)}}
function openPhoto(id,name){compressedPhoto="";$("photoAthleteId").value=id;$("photoAthleteName").textContent=name;$("athletePhoto").value="";$("photoConsent").checked=false;$("photoPreview").textContent="Pratonton gambar akan muncul di sini.";clearMessage($("photoMessage"));$("photoDialog").showModal()}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type))return reject(Error("Pilih gambar JPG, PNG atau WebP."));const reader=new FileReader();reader.onerror=()=>reject(Error("Gambar tidak dapat dibaca."));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(Error("Format gambar tidak dapat diproses."));image.onload=()=>{const size=320,scale=Math.min(1,size/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);let quality=.76,data=canvas.toDataURL("image/jpeg",quality);while(data.length>47000&&quality>.35){quality-=.08;data=canvas.toDataURL("image/jpeg",quality)}if(data.length>48000)return reject(Error("Gambar terlalu besar walaupun selepas dimampatkan."));resolve(data)};image.src=reader.result};reader.readAsDataURL(file)})}
async function previewPhoto(){try{compressedPhoto=await compressImage($("athletePhoto").files[0]);$("photoPreview").innerHTML=`<img src="${compressedPhoto}" alt="Pratonton gambar atlet"><span>Gambar akan dipaparkan berbentuk potret pada dashboard.</span>`;clearMessage($("photoMessage"))}catch(error){compressedPhoto="";message($("photoMessage"),error.message)}}
async function savePhoto(event){event.preventDefault();const button=event.submitter;if(!compressedPhoto){message($("photoMessage"),"Pilih dan tunggu pratonton gambar siap dahulu.");return}setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveAthletePhoto",token:session.token,year:currentYear(),athleteId:$("photoAthleteId").value,photo:compressedPhoto,consent:$("photoConsent").checked?"YA":"TIDAK"});message($("photoMessage"),result.message,"success");setTimeout(()=>$("photoDialog").close(),650)}catch(error){message($("photoMessage"),error.message)}finally{setBusy(button,false)}}
function renderProfile(){
  const house=workspaceData.house||currentHouse(),profile=workspaceData.profile||{},items=[["Nama rumah",house?`Rumah ${house}`:"Semua rumah"],["Moto",profile.motto],["Slogan",profile.slogan],["Ketua rumah",profile.captain],["Pemegang sepanduk",profile.bannerBearer],["Pemegang bendera",profile.flagBearer]],letter=house?house[0]:"R";
  const media=[["members","Senarai Ahli",profile.memberImage,"👥"],["marching","Barisan Kawad",profile.marchingImage,"🥁"],["participants","Peserta & Acara",profile.participantImage,"🏃"]];
  $("profileDetails").innerHTML=`<article class="house-logo-manager"><div class="house-logo-current">${profile.logo?`<img src="${safe(profile.logo)}" alt="Logo Rumah ${safe(house)}">`:`<span style="--house:${HOUSE_COLORS[house]||"#246bfd"}">${safe(letter)}</span>`}</div><div><small>LOGO RUMAH ${safe(house).toUpperCase()}</small><b>${profile.logo?"Logo rumah sedang digunakan":"Gunakan logo khas pasukan sendiri"}</b><p>Guru Rumah ${safe(house)} boleh menukar logo rumah ini. Admin boleh mengurus logo bagi mana-mana rumah yang dipilih.</p><div><button class="row-action" type="button" id="changeHouseLogo">${profile.logo?"Tukar logo":"Muat naik logo"}</button>${profile.logo?'<button class="row-action danger" type="button" id="removeHouseLogo">Buang logo</button>':""}</div></div></article><article class="house-media-manager"><div><small>GAMBAR HEADER PROFIL</small><b>Hidupkan halaman Rumah ${safe(house)}</b><p>Muat naik gambar pasukan untuk tiga bahagian profil awam. Guru hanya boleh mengurus gambar rumah sendiri.</p></div><div class="house-media-grid">${media.map(([slot,label,image,icon])=>`<section>${image?`<img src="${safe(image)}" alt="${safe(label)}">`:`<span>${icon}</span>`}<b>${safe(label)}</b><button class="row-action" type="button" data-house-media="${slot}" data-media-label="${safe(label)}">${image?"Tukar gambar":"Muat naik"}</button>${image?`<button class="media-remove" type="button" data-remove-media="${slot}" data-media-label="${safe(label)}">Buang</button>`:""}</section>`).join("")}</div></article>`+items.map(([label,value])=>`<article><small>${safe(label)}</small><b>${safe(value||"Belum diisi")}</b></article>`).join("");
  $("profileDetails").innerHTML=$("profileDetails").innerHTML.replace("Admin boleh mengurus logo","Admin Sistem boleh mengurus logo");
  $("changeHouseLogo").onclick=openHouseLogo;if($("removeHouseLogo"))$("removeHouseLogo").onclick=removeHouseLogo;
  document.querySelectorAll("[data-house-media]").forEach(button=>button.onclick=()=>openHouseMedia(button.dataset.houseMedia,button.dataset.mediaLabel));document.querySelectorAll("[data-remove-media]").forEach(button=>button.onclick=()=>removeHouseMedia(button.dataset.removeMedia,button.dataset.mediaLabel));
}
function openHouseLogo(){compressedHouseLogo="";$("houseLogoFile").value="";$("houseLogoPreview").innerHTML='<div class="logo-placeholder">Pilih logo berbentuk segi empat. PNG berlatar telus paling sesuai.</div>';clearMessage($("houseLogoMessage"));$("houseLogoDialog").showModal()}
async function compressHouseLogo(file){if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw Error("Pilih fail JPG, PNG atau WebP.");const bitmap=await createImageBitmap(file),canvas=document.createElement("canvas"),size=360;canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");ctx.clearRect(0,0,size,size);const scale=Math.min(size/bitmap.width,size/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;ctx.drawImage(bitmap,(size-w)/2,(size-h)/2,w,h);bitmap.close();let quality=.86,data=canvas.toDataURL("image/webp",quality);while(data.length>48000&&quality>.3){quality-=.1;data=canvas.toDataURL("image/webp",quality)}if(data.length>48000)throw Error("Gambar terlalu besar. Cuba logo yang lebih ringkas.");return data}
async function previewHouseLogo(){const file=$("houseLogoFile").files[0];if(!file)return;clearMessage($("houseLogoMessage"));$("houseLogoPreview").textContent="Sedang menyediakan logo…";try{compressedHouseLogo=await compressHouseLogo(file);$("houseLogoPreview").innerHTML=`<img src="${compressedHouseLogo}" alt="Pratonton logo rumah">`}catch(error){compressedHouseLogo="";message($("houseLogoMessage"),error.message)}}
async function saveHouseLogo(event){event.preventDefault();const button=event.submitter;if(!compressedHouseLogo){message($("houseLogoMessage"),"Pilih dan tunggu pratonton logo siap dahulu.");return}setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveHouseLogo",token:session.token,year:currentYear(),house:currentHouse(),logo:compressedHouseLogo});message($("houseLogoMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("houseLogoDialog").close(),600)}catch(error){message($("houseLogoMessage"),error.message)}finally{setBusy(button,false)}}
async function removeHouseLogo(){if(!confirm(`Buang logo Rumah ${currentHouse()}? Logo sementara akan digunakan semula.`))return;try{const result=await api({action:"saveHouseLogo",token:session.token,year:currentYear(),house:currentHouse(),logo:""});alert(result.message);await loadWorkspace()}catch(error){alert(error.message)}}
function openHouseMedia(slot,label){currentHouseMediaSlot=slot;compressedHouseMedia="";$("houseMediaTitle").textContent=`Gambar ${label}`;$("houseMediaFile").value="";$("houseMediaPreview").innerHTML='<div class="logo-placeholder">Pilih gambar landskap yang cerah dan jelas.</div>';clearMessage($("houseMediaMessage"));$("houseMediaDialog").showModal()}
async function compressHouseMedia(file){if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw Error("Pilih fail JPG, PNG atau WebP.");const bitmap=await createImageBitmap(file),canvas=document.createElement("canvas"),width=720,height=360;canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d"),scale=Math.max(width/bitmap.width,height/bitmap.height),w=bitmap.width*scale,h=bitmap.height*scale;ctx.drawImage(bitmap,(width-w)/2,(height-h)/2,w,h);bitmap.close();let quality=.78,data=canvas.toDataURL("image/webp",quality);while(data.length>48000&&quality>.25){quality-=.08;data=canvas.toDataURL("image/webp",quality)}if(data.length>48000)throw Error("Gambar terlalu besar. Cuba gambar lain.");return data}
async function previewHouseMedia(){const file=$("houseMediaFile").files[0];if(!file)return;clearMessage($("houseMediaMessage"));$("houseMediaPreview").textContent="Sedang menyediakan gambar…";try{compressedHouseMedia=await compressHouseMedia(file);$("houseMediaPreview").innerHTML=`<img src="${compressedHouseMedia}" alt="Pratonton gambar header">`}catch(error){compressedHouseMedia="";message($("houseMediaMessage"),error.message)}}
async function saveHouseMedia(event){event.preventDefault();const button=event.submitter;if(!compressedHouseMedia){message($("houseMediaMessage"),"Pilih dan tunggu pratonton gambar siap dahulu.");return}setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveHouseMedia",token:session.token,year:currentYear(),house:currentHouse(),slot:currentHouseMediaSlot,image:compressedHouseMedia});message($("houseMediaMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("houseMediaDialog").close(),600)}catch(error){message($("houseMediaMessage"),error.message)}finally{setBusy(button,false)}}
async function removeHouseMedia(slot,label){if(!confirm(`Buang gambar ${label} untuk Rumah ${currentHouse()}?`))return;try{const result=await api({action:"saveHouseMedia",token:session.token,year:currentYear(),house:currentHouse(),slot,image:""});alert(result.message);await loadWorkspace()}catch(error){alert(error.message)}}
function openPupil(id=""){
  const row=(workspaceData?.pupils||[]).find(x=>x.id===id)||{};$("pupilDialogTitle").textContent=id?"Edit murid":"Tambah murid";$("pupilId").value=row.id||"";$("pupilName").value=row.name||"";$("pupilClass").value=row.class||"";$("pupilGender").value=normalizeGender(row.gender);clearMessage($("pupilMessage"));$("pupilDialog").showModal();
}
function normalizeGender(value){const text=String(value||"").toUpperCase();return/^(L|LELAKI|M|MALE)$/.test(text)?"Lelaki":/^(P|PEREMPUAN|F|FEMALE)$/.test(text)?"Perempuan":""}
function pupilYear(value){const text=String(value||"").toUpperCase();if(/PRA/.test(text))return 0;const match=text.match(/(?:TAHUN\s*)?([1-6])/);return match?Number(match[1]):-1}
function eligibleEvents(pupil){
  const year=pupilYear(pupil.class),gender=normalizeGender(pupil.gender);return(workspaceData?.events||[]).filter(event=>{const allowed=(String(event.cohort||"").match(/[1-6]/g)||[]).map(Number),cohort=/PRA/i.test(event.cohort||"")?year===0:allowed.includes(year);return cohort&&(!normalizeGender(event.gender)||normalizeGender(event.gender)===gender)});
}
function openEntry(){
  const pupils=workspaceData?.pupils||[];$("entryPupil").innerHTML='<option value="">Pilih murid</option>'+pupils.map(row=>`<option value="${safe(row.id)}">${safe(row.name)} • ${safe(row.class)}</option>`).join("");$("entryEvent").innerHTML='<option value="">Pilih murid dahulu</option>';clearMessage($("entryMessage"));$("entryDialog").showModal();
}
function updateEligibleEvents(){
  const pupil=(workspaceData?.pupils||[]).find(row=>row.id===$("entryPupil").value),events=pupil?eligibleEvents(pupil):[];$("entryEvent").innerHTML='<option value="">Pilih acara</option>'+events.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.cohort)} • ${safe(event.type)}</option>`).join("");$("entryEligibility").textContent=pupil?`${events.length} acara sepadan untuk ${pupil.name}. Sistem akan menyemak had dan kuota sekali lagi sebelum menyimpan.`:"Pilih murid untuk memaparkan acara yang sepadan dengan kategori dan jantina.";
}
async function savePupil(event){event.preventDefault();const button=event.submitter;clearMessage($("pupilMessage"));setBusy(button,true,"Menyimpan…");try{await api({action:"savePupil",token:session.token,year:currentYear(),house:currentHouse(),id:$("pupilId").value,name:$("pupilName").value,class:$("pupilClass").value,gender:$("pupilGender").value});message($("pupilMessage"),"Maklumat murid berjaya disimpan.","success");await loadWorkspace();setTimeout(()=>$("pupilDialog").close(),450)}catch(error){message($("pupilMessage"),error.message)}finally{setBusy(button,false)}}
async function saveEntry(event){event.preventDefault();const button=event.submitter;clearMessage($("entryMessage"));setBusy(button,true,"Menyemak syarat…");try{const result=await api({action:"saveEntry",token:session.token,year:currentYear(),house:currentHouse(),pupilId:$("entryPupil").value,eventId:$("entryEvent").value});message($("entryMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("entryDialog").close(),500)}catch(error){message($("entryMessage"),error.message)}finally{setBusy(button,false)}}
function openEntryCancellation(id,name,eventName){if(!isAdmin()){alert("Hanya Admin Sistem boleh membatalkan penyertaan atlet.");return}$("entryCancelId").value=id;$("entryCancelReason").value="";$("entryCancelNote").value="";$("entryCancelSummary").textContent=`${name||"Atlet ini"} • ${eventName||"Acara dipilih"}. Hanya penyertaan ini akan dibatalkan.`;clearMessage($("entryCancelMessage"));$("entryCancelDialog").showModal()}
async function deleteEntry(event){event.preventDefault();if(!isAdmin()){message($("entryCancelMessage"),"Hanya Admin Sistem boleh membatalkan penyertaan atlet.");return}const reason=$("entryCancelReason").value,note=$("entryCancelNote").value.trim();if(reason==="Lain-lain"&&!note){message($("entryCancelMessage"),"Nyatakan catatan apabila memilih sebab Lain-lain.");return}const button=event.submitter;setBusy(button,true,"Membatalkan…");try{const result=await api({action:"deleteEntry",token:session.token,id:$("entryCancelId").value,reason,note});message($("entryCancelMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("entryCancelDialog").close(),650)}catch(error){message($("entryCancelMessage"),error.message)}finally{setBusy(button,false)}}
function openProfile(){const p=workspaceData?.profile||{};$("profileMotto").value=p.motto||"";$("profileSlogan").value=p.slogan||"";$("profileCaptain").value=p.captain||"";$("profileBannerBearer").value=p.bannerBearer||"";$("profileFlagBearer").value=p.flagBearer||"";clearMessage($("profileMessage"));$("profileDialog").showModal()}
async function saveProfile(event){event.preventDefault();const button=event.submitter;clearMessage($("profileMessage"));setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveHouseProfile",token:session.token,year:currentYear(),house:currentHouse(),motto:$("profileMotto").value,slogan:$("profileSlogan").value,captain:$("profileCaptain").value,bannerBearer:$("profileBannerBearer").value,flagBearer:$("profileFlagBearer").value});message($("profileMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("profileDialog").close(),450)}catch(error){message($("profileMessage"),error.message)}finally{setBusy(button,false)}}
function maskIc(ic){const x=String(ic||"").replace(/\D/g,"");return x.length===12?`${x.slice(0,2)}••••••${x.slice(-4)}`:"—"}
function renderUsers(){
  const house=workspaceData?.house||currentHouse();$("houseUsersTitle").textContent=house?`Guru Rumah ${house}`:"Guru rumah sukan";
  const header=`<div class="secure-row user-row secure-head"><span>ID</span><span>Nama guru</span><span>Peranan</span><span>MyKad</span><span>Status</span></div>`;
  const body=adminUsers.map(user=>{const content=`<span>${safe(user.id)}</span><b>${safe(user.name)}</b><span>${safe(user.role||`Guru Rumah ${house}`)}</span><span>${safe(user.maskedIc||maskIc(user.ic))}</span><em>${user.active?(user.mustChange?"Perlu tukar kata laluan":"Aktif"):"Tidak aktif"}</em>`;return isAdmin()?`<button class="secure-row user-row user-row-button" data-edit-user="${safe(user.id)}">${content}</button>`:`<div class="secure-row user-row">${content}</div>`}).join("");
  $("userRows").innerHTML=adminUsers.length?header+body:`<div class="secure-empty">Belum ada akaun guru untuk Rumah ${safe(house)}.</div>`;
  if(isAdmin())document.querySelectorAll("[data-edit-user]").forEach(button=>button.onclick=()=>openUser(button.dataset.editUser));
}
function renderJudgeAccess(){
  if(!isAdmin()||!$("judgeAccessRows"))return;const rows=workspaceData?.judgeAccess||[];
  const header='<div class="secure-row judge-access-row secure-head"><span>ID</span><span>Nama petugas</span><span>Peranan</span><span>Skop acara</span><span>Kod akses</span><span>Tindakan</span></div>';
  $("judgeAccessRows").innerHTML=rows.length?header+rows.map(row=>`<div class="secure-row judge-access-row"><span>${safe(row.id)}</span><b>${safe(row.name)}</b><span>${safe(row.role)}</span><span>${safe(row.scope)}</span><span class="judge-code"><code>${safe(row.code)}</code><button type="button" data-copy-judge="${safe(row.code)}">Salin</button></span><button type="button" data-edit-judge="${safe(row.id)}">${row.active?"Edit":"Tidak aktif"}</button></div>`).join(""):'<div class="secure-empty">Belum ada kod pengadil. Tekan “Jana kod permulaan” untuk menyediakan akses Balapan, Relay, Lompat Jauh, Lompat Tinggi dan Lontar Peluru.</div>';
  document.querySelectorAll("[data-copy-judge]").forEach(button=>button.onclick=async()=>{try{await navigator.clipboard.writeText(button.dataset.copyJudge);button.textContent="Disalin ✓";setTimeout(()=>button.textContent="Salin",1200)}catch{prompt("Salin kod akses pengadil:",button.dataset.copyJudge)}});
  document.querySelectorAll("[data-edit-judge]").forEach(button=>button.onclick=()=>openJudgeAccess(button.dataset.editJudge));
}
function openJudgeAccess(id=""){const row=(workspaceData?.judgeAccess||[]).find(item=>item.id===id)||{};$("judgeAccessId").value=row.id||"";$("judgeAccessName").value=row.name||"";$("judgeAccessRole").value=row.role||"Pengadil Balapan";$("judgeAccessScope").value=row.scope||"BALAPAN";$("judgeAccessCode").value=row.code||"";$("judgeAccessActive").value=row.active===false?"TIDAK":"YA";$("judgeAccessReset").checked=false;clearMessage($("judgeAccessMessage"));$("judgeAccessDialog").showModal()}
async function saveJudgeAccess(event){event.preventDefault();const button=event.submitter;setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveJudgeAccess",token:session.token,id:$("judgeAccessId").value,name:$("judgeAccessName").value,role:$("judgeAccessRole").value,scope:$("judgeAccessScope").value,code:$("judgeAccessCode").value,active:$("judgeAccessActive").value,reset:$("judgeAccessReset").checked?"YA":"TIDAK"});message($("judgeAccessMessage"),`${result.message} Kod: ${result.code}`,"success");await loadWorkspace();setTimeout(()=>$("judgeAccessDialog").close(),900)}catch(error){message($("judgeAccessMessage"),error.message)}finally{setBusy(button,false)}}
async function seedJudgeAccess(){if(!confirm("Jana lima kod permulaan untuk Balapan, Relay, Lompat Jauh, Lompat Tinggi dan Lontar Peluru?"))return;const button=$("seedJudgeButton");setBusy(button,true,"Menjana…");try{const result=await api({action:"seedJudgeAccess",token:session.token});alert(result.message);await loadWorkspace()}catch(error){alert(error.message)}finally{setBusy(button,false)}}
function filteredAudit(){
  const query=$("auditSearch")?.value.trim().toLowerCase()||"",house=$("auditHouse")?.value||"";
  return(workspaceData?.auditLogs||[]).filter(row=>(!house||row.house===house)&&(!query||`${row.teacher} ${row.teacherId} ${row.action} ${row.target} ${row.detail}`.toLowerCase().includes(query)));
}
function renderAudit(){
  if(!isAdmin()||!$("auditRows"))return;const rows=filteredAudit();$("auditSummary").textContent=`${rows.length} daripada ${(workspaceData?.auditLogs||[]).length} rekod terkini dipaparkan.`;
  const header='<div class="secure-row audit-row secure-head"><span>Masa</span><span>Guru / rumah</span><span>Tindakan</span><span>Sasaran & butiran</span></div>';
  $("auditRows").innerHTML=rows.length?header+rows.map(row=>`<div class="secure-row audit-row"><time>${safe(row.date||"—")}</time><span><b>${safe(row.teacher||row.teacherId||"Sistem")}</b><small>${safe(row.house?`Rumah ${row.house}`:row.teacherId||"Admin Sistem")}</small></span><em>${safe(row.action||"—")}</em><span><b>${safe(row.target||"—")}</b><small>${safe(row.detail||"Tiada butiran")}</small></span></div>`).join(""):'<div class="secure-empty">Tiada rekod audit yang sepadan.</div>';
}
function exportAudit(){
  const rows=filteredAudit(),quote=value=>`"${String(value??"").replace(/"/g,'""')}"`,csv=[["Tarikh Masa","ID Guru","Nama Guru","Rumah","Tindakan","Sasaran","Butiran"],...rows.map(row=>[row.date,row.teacherId,row.teacher,row.house,row.action,row.target,row.detail])].map(line=>line.map(quote).join(",")).join("\r\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`log-audit-skrg-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);
}
function openUser(id=""){const user=adminUsers.find(x=>x.id===id)||{};$("userId").value=user.id||"";$("userId").readOnly=Boolean(id);$("userIc").value=user.ic||"";$("userName").value=user.name||"";$("userHouse").value=user.house||"";$("userRole").value=user.role||"Guru Rumah";$("userActive").value=user.active===false?"TIDAK":"YA";$("resetUserPassword").hidden=!id;$("resetUserPassword").dataset.id=id;clearMessage($("userMessage"));$("userDialog").showModal()}
async function saveUser(event){event.preventDefault();const button=event.submitter;clearMessage($("userMessage"));setBusy(button,true,"Menyimpan…");try{const result=await api({action:"saveUser",token:session.token,id:$("userId").value,ic:$("userIc").value,name:$("userName").value,house:$("userHouse").value,role:$("userRole").value,active:$("userActive").value});message($("userMessage"),result.message,"success");await loadWorkspace();setTimeout(()=>$("userDialog").close(),450)}catch(error){message($("userMessage"),error.message)}finally{setBusy(button,false)}}
async function resetUser(){const id=$("resetUserPassword").dataset.id;if(!id||!confirm("Tetapkan semula kata laluan guru ini kepada kata laluan sementara?"))return;try{const result=await api({action:"resetPassword",token:session.token,id});message($("userMessage"),result.message||"Kata laluan berjaya ditetapkan semula.","success");await loadWorkspace()}catch(error){message($("userMessage"),error.message)}}
async function saveSettings(event){event.preventDefault();const button=event.submitter;clearMessage($("settingsMessage"));setBusy(button,true,"Menyimpan…");try{const values={bannerUrl:$("bannerUrl").value,tickerText:$("tickerText").value,tickerActive:$("tickerActive").value};const result=await api({action:"saveSettings",token:session.token,...values});message($("settingsMessage"),result.message,"success");workspaceData.settings={bannerUrl:values.bannerUrl,tickerText:values.tickerText,tickerActive:values.tickerActive==="YA"}}catch(error){message($("settingsMessage"),error.message)}finally{setBusy(button,false)}}
async function logout(){try{if(session?.token)await api({action:"logout",token:session.token})}catch{}localStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY);location.reload()}
function switchTab(button){document.querySelectorAll("[data-workspace-tab]").forEach(x=>x.classList.toggle("active",x===button));["pupils","entries","results","profile","rules","users","judges","audit","settings"].forEach(name=>$(name+"Panel").hidden=name!==button.dataset.workspaceTab)}

function updateClock(){const now=new Date(),date=new Intl.DateTimeFormat("ms-MY",{timeZone:"Asia/Kuching",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now),time=new Intl.DateTimeFormat("ms-MY",{timeZone:"Asia/Kuching",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:true}).format(now);const value=`${date} • ${time}`;["headerClock","footerClock"].forEach(id=>{if($(id))$(id).textContent=value})}
updateClock();setInterval(updateClock,1000);

$("loginForm").addEventListener("submit",login);$("adminAccessForm").addEventListener("submit",adminLogin);$("adminAccessButton").addEventListener("click",()=>{clearMessage($("adminAccessMessage"));$("adminAccessCode").value="";$("adminAccessDialog").showModal()});$("teacherIc").addEventListener("input",()=>{$("teacherIc").value=$("teacherIc").value.replace(/[^0-9-]/g,"");$("teacherPreview").hidden=true});$("teacherIc").addEventListener("blur",previewTeacher);$("changePasswordForm").addEventListener("submit",changePassword);$("logoutButton").addEventListener("click",logout);$("workspaceYear").addEventListener("change",loadWorkspace);$("workspaceHouseSelect").addEventListener("change",loadWorkspace);$("pupilSearch").addEventListener("input",renderPupils);$("forgotButton").addEventListener("click",()=>$("adminHelpDialog").showModal());
$("addPupilButton").addEventListener("click",()=>openPupil());$("addEntryButton").addEventListener("click",openEntry);$("addResultButton").addEventListener("click",openResult);$("editProfileButton").addEventListener("click",openProfile);$("addUserButton").addEventListener("click",()=>openUser());$("addJudgeButton").addEventListener("click",()=>openJudgeAccess());$("seedJudgeButton").addEventListener("click",seedJudgeAccess);$("judgeAccessForm").addEventListener("submit",saveJudgeAccess);$("entryPupil").addEventListener("change",updateEligibleEvents);$("entryCancelForm").addEventListener("submit",deleteEntry);$("resultEvent").addEventListener("change",updateResultContestants);$("resultEventFilter").addEventListener("change",renderResults);$("athletePhoto").addEventListener("change",previewPhoto);$("houseLogoFile").addEventListener("change",previewHouseLogo);$("houseMediaFile").addEventListener("change",previewHouseMedia);$("pupilForm").addEventListener("submit",savePupil);$("entryForm").addEventListener("submit",saveEntry);$("resultForm").addEventListener("submit",saveResult);$("photoForm").addEventListener("submit",savePhoto);$("houseLogoForm").addEventListener("submit",saveHouseLogo);$("houseMediaForm").addEventListener("submit",saveHouseMedia);$("profileForm").addEventListener("submit",saveProfile);$("userForm").addEventListener("submit",saveUser);$("resetUserPassword").addEventListener("click",resetUser);$("settingsForm").addEventListener("submit",saveSettings);$("auditSearch").addEventListener("input",renderAudit);$("auditHouse").addEventListener("change",renderAudit);$("auditExport").addEventListener("click",exportAudit);
document.querySelectorAll("[data-workspace-tab]").forEach(button=>button.addEventListener("click",()=>switchTab(button)));document.querySelectorAll("[data-close-dialog]").forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));document.querySelectorAll("[data-toggle-password]").forEach(button=>button.addEventListener("click",()=>{const input=$(button.dataset.togglePassword);input.type=input.type==="password"?"text":"password";button.textContent=input.type==="password"?"Lihat":"Sorok"}));
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||sessionStorage.getItem(SESSION_KEY)||"null")}catch{session=null}if(session?.token&&session?.user){if(session.mustChange)$("changePasswordDialog").showModal();else openWorkspace()}
