const JUDGE_API="https://script.google.com/macros/s/AKfycbx3r8_KKM-jHIpPoL6dEa-IKIXZqfjxWDr3jJQF8AC2QvjL7MUrEGBuoNRkvpG9k6lnhQ/exec";
const JUDGE_SESSION_KEY="skrg_judge_session";
const TEACHER_SESSION_KEY="skrg_teacher_session";
const CATEGORY_ORDER=["Prasekolah","Tahun 1","Tahun 2 & Tahun 3","Tahun 4 & Tahun 5","Tahun 6"];
const $=id=>document.getElementById(id);
const safe=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let judgeSession=null,judgeData=null,activeJudgeCategory="";
async function judgeApi(payload){const response=await fetch(JUDGE_API,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams(payload),redirect:"follow",cache:"no-store"});if(!response.ok)throw Error("Pelayan data tidak dapat dihubungi.");const data=await response.json();if(data.error)throw Error(data.message||"Permintaan tidak berjaya.");return data}
function judgeMessage(target,text,type="error"){target.textContent=text;target.className=`form-message ${type}`}
function judgeBusy(button,busy,label){button.disabled=busy;button.dataset.label=button.dataset.label||button.textContent;button.textContent=busy?label:button.dataset.label}
function isRelay(event){return /berkumpul|relay|4\s*[×x]/i.test(`${event?.type||""} ${event?.name||""}`)}
function teacherToken(){try{const saved=JSON.parse(localStorage.getItem(TEACHER_SESSION_KEY)||sessionStorage.getItem(TEACHER_SESSION_KEY)||"null");return saved?.token||""}catch{return ""}}
function categoryOf(event){const text=String(event?.cohort||event?.category||"").toUpperCase().replace(/\s+/g," ").trim();if(/PRA/.test(text))return "Prasekolah";if(/(^|\D)1(\D|$)/.test(text)&&!/2|3/.test(text))return "Tahun 1";if(/2/.test(text)&&/3/.test(text))return "Tahun 2 & Tahun 3";if(/4/.test(text)&&/5/.test(text))return "Tahun 4 & Tahun 5";if(/(^|\D)6(\D|$)/.test(text))return "Tahun 6";return event?.cohort||event?.category||"Kategori lain"}
function categoryEvents(){return (judgeData?.events||[]).filter(event=>categoryOf(event)===activeJudgeCategory)}
async function loginJudge(event){event.preventDefault();const button=event.submitter;judgeBusy(button,true,"Menyemak…");judgeMessage($("judgeLoginMessage"),"");try{const result=await judgeApi({action:"judgeLogin",code:$("judgeCode").value.trim(),teacherToken:teacherToken()});judgeSession={token:result.token,user:result.user};sessionStorage.setItem(JUDGE_SESSION_KEY,JSON.stringify(judgeSession));await openJudgeWorkspace()}catch(error){judgeMessage($("judgeLoginMessage"),error.message)}finally{judgeBusy(button,false)}}
async function openJudgeWorkspace(){$("judgeIntro").hidden=true;$("judgeWorkspace").hidden=false;$("judgeName").textContent=judgeSession.user.name||"Pengadil";const identity=judgeSession.user.identityType==="AWAM"?"PETUGAS AWAM":`${judgeSession.user.schoolRole||"Warga Sekolah"}${judgeSession.user.house?` • Rumah ${judgeSession.user.house}`:""}`;$("judgeScope").textContent=`${identity} • ${judgeSession.user.judgeLabel||judgeSession.user.role||"Pengadil"} • Skop: ${judgeSession.user.judgeScope||"Semua acara"}`;await loadJudgeData()}
async function loadJudgeData(){try{judgeData=await judgeApi({action:"judgeData",token:judgeSession.token,year:$("judgeYear").value});renderJudgeWorkspace()}catch(error){if(/sesi/i.test(error.message)){logoutJudge();return}alert(error.message)}}
function renderJudgeWorkspace(){const events=judgeData.events||[],entries=judgeData.entries||[],results=judgeData.results||[];const available=[...new Set(events.map(categoryOf))].sort((a,b)=>{const ai=CATEGORY_ORDER.indexOf(a),bi=CATEGORY_ORDER.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)});if(!available.includes(activeJudgeCategory))activeJudgeCategory=available[0]||"";$("judgeEventCount").textContent=events.length;$("judgeEntryCount").textContent=entries.length;$("judgeResultCount").textContent=results.length;$("judgeCategoryTabs").innerHTML=available.map(category=>`<button type="button" class="${category===activeJudgeCategory?"active":""}" data-judge-category="${safe(category)}"><span>${safe(category)}</span><b>${events.filter(event=>categoryOf(event)===category).length} acara</b></button>`).join("");document.querySelectorAll("[data-judge-category]").forEach(button=>button.onclick=()=>{activeJudgeCategory=button.dataset.judgeCategory;renderJudgeWorkspace()});const shown=categoryEvents();$("judgeCategoryTitle").textContent=activeJudgeCategory?`Kategori ${activeJudgeCategory}`:"Tiada kategori ditugaskan";$("judgeEventGrid").innerHTML=shown.length?shown.map(event=>{const count=entries.filter(row=>row.eventId===event.id).length,done=results.filter(row=>row.eventId===event.id).length;return `<button type="button" data-judge-event="${safe(event.id)}"><small>${safe(event.discipline||"Acara")} • ${safe(event.gender)}</small><b>${safe(event.name)}</b><span>${event.mode==="higher"?"📏 Ukuran tertinggi":"⏱ Masa terendah"}</span><em>${done}/${isRelay(event)?4:count} catatan tersedia</em></button>`}).join(""):'<div class="secure-empty">Tiada acara dalam kategori ini untuk kod akses tersebut.</div>';document.querySelectorAll("[data-judge-event]").forEach(button=>button.onclick=()=>openJudgeResult(button.dataset.judgeEvent));const filter=$("judgeResultFilter"),selected=filter.value;filter.innerHTML='<option value="">Semua acara kategori ini</option>'+shown.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.gender)}</option>`).join("");filter.value=shown.some(event=>event.id===selected)?selected:"";renderJudgeResults()}
function renderJudgeResults(){const filter=$("judgeResultFilter").value,allowed=new Set(categoryEvents().map(event=>event.id)),rows=(judgeData?.results||[]).filter(row=>allowed.has(row.eventId)&&(!filter||row.eventId===filter));$("judgeResultRows").innerHTML=rows.length?'<div class="secure-row judge-result-row secure-head"><span>Ked.</span><span>Acara / peserta</span><span>Rumah</span><span>Catatan</span><span>Direkod oleh</span></div>'+rows.map(row=>`<div class="secure-row judge-result-row"><b class="place-badge place-${safe(row.place)}">${safe(row.place||"—")}</b><span><strong>${safe(row.event)}</strong><small>${safe(row.athlete||`Pasukan Rumah ${row.house}`)} • ${safe(row.category)}</small></span><span>${safe(row.house)}</span><b>${safe(row.mark||`${row.value} ${row.unit}`)}</b><small>${safe(row.recordedBy||"—")}</small></div>`).join(""):'<div class="secure-empty">Belum ada catatan rasmi untuk kategori ini.</div>'}
function openJudgeResult(eventId=""){const events=categoryEvents();$("judgeEvent").innerHTML='<option value="">Pilih acara</option>'+events.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.gender)}</option>`).join("");$("judgeEvent").value=eventId;$("judgeValue").value="";$("judgeResultMessage").textContent="";updateJudgeContestants();$("judgeResultDialog").showModal()}
function updateJudgeContestants(){const event=(judgeData?.events||[]).find(row=>row.id===$("judgeEvent").value),entries=(judgeData?.entries||[]).filter(row=>row.eventId===event?.id),relay=isRelay(event);if(!event){$("judgeContestant").innerHTML='<option value="">Pilih acara dahulu</option>';return}if(relay){const houses=[...new Set(entries.map(row=>row.house).filter(Boolean))];$("judgeContestant").innerHTML='<option value="">Pilih pasukan rumah</option>'+houses.map(house=>`<option value="${safe(house)}">Pasukan Rumah ${safe(house)}</option>`).join("")}else $("judgeContestant").innerHTML='<option value="">Pilih peserta</option>'+entries.map(row=>`<option value="${safe(row.pupilId)}">${safe(row.name)} • Rumah ${safe(row.house)}</option>`).join("");$("judgeUnit").value=event.unit||"saat";$("judgeUnit").disabled=true;$("judgeValueLabel").textContent=event.mode==="higher"?"Ukuran terbaik":"Masa larian";$("judgeGuidance").textContent=event.mode==="higher"?"Masukkan ukuran dalam meter. Nilai paling tinggi menerima kedudukan pertama.":"Masukkan masa dalam saat. Nilai paling rendah menerima kedudukan pertama."}
async function saveJudgeResult(event){event.preventDefault();const button=event.submitter,eventInfo=(judgeData?.events||[]).find(row=>row.id===$("judgeEvent").value),relay=isRelay(eventInfo);judgeBusy(button,true,"Menyimpan…");try{const result=await judgeApi({action:"saveResult",token:judgeSession.token,year:$("judgeYear").value,eventId:$("judgeEvent").value,athleteId:relay?"":$("judgeContestant").value,house:relay?$("judgeContestant").value:"",value:$("judgeValue").value,unit:$("judgeUnit").value});judgeMessage($("judgeResultMessage"),result.message,"success");await loadJudgeData();setTimeout(()=>$("judgeResultDialog").close(),650)}catch(error){judgeMessage($("judgeResultMessage"),error.message)}finally{judgeBusy(button,false)}}
function logoutJudge(){sessionStorage.removeItem(JUDGE_SESSION_KEY);location.reload()}
$("judgeLoginForm").addEventListener("submit",loginJudge);$("judgeYear").addEventListener("change",()=>{activeJudgeCategory="";loadJudgeData()});$("judgeLogout").addEventListener("click",logoutJudge);$("newJudgeResult").addEventListener("click",()=>openJudgeResult());$("judgeEvent").addEventListener("change",updateJudgeContestants);$("judgeResultFilter").addEventListener("change",renderJudgeResults);$("judgeResultForm").addEventListener("submit",saveJudgeResult);document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>button.closest("dialog").close());try{judgeSession=JSON.parse(sessionStorage.getItem(JUDGE_SESSION_KEY)||"null")}catch{judgeSession=null}if(judgeSession?.token)openJudgeWorkspace();
