const JUDGE_API="https://script.google.com/macros/s/AKfycbx3r8_KKM-jHIpPoL6dEa-IKIXZqfjxWDr3jJQF8AC2QvjL7MUrEGBuoNRkvpG9k6lnhQ/exec";
const JUDGE_SESSION_KEY="skrg_judge_session";
const $=id=>document.getElementById(id);
const safe=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let judgeSession=null,judgeData=null;
async function judgeApi(payload){const response=await fetch(JUDGE_API,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"},body:new URLSearchParams(payload),redirect:"follow",cache:"no-store"});if(!response.ok)throw Error("Pelayan data tidak dapat dihubungi.");const data=await response.json();if(data.error)throw Error(data.message||"Permintaan tidak berjaya.");return data}
function judgeMessage(target,text,type="error"){target.textContent=text;target.className=`form-message ${type}`}
function judgeBusy(button,busy,label){button.disabled=busy;button.dataset.label=button.dataset.label||button.textContent;button.textContent=busy?label:button.dataset.label}
function isRelay(event){return /berkumpul|relay|4\s*[×x]/i.test(`${event?.type||""} ${event?.name||""}`)}
function updateJudgeIdentity(){const warga=$("judgeIdentityType").value==="WARGA";$("judgeIcField").hidden=!warga;$("judgeIc").required=warga;if(!warga)$("judgeIc").value=""}
async function loginJudge(event){event.preventDefault();const button=event.submitter;judgeBusy(button,true,"Menyemak…");judgeMessage($("judgeLoginMessage"),"");try{const result=await judgeApi({action:"judgeLogin",code:$("judgeCode").value.trim(),identityType:$("judgeIdentityType").value,ic:$("judgeIc").value});judgeSession={token:result.token,user:result.user};sessionStorage.setItem(JUDGE_SESSION_KEY,JSON.stringify(judgeSession));await openJudgeWorkspace()}catch(error){judgeMessage($("judgeLoginMessage"),error.message)}finally{judgeBusy(button,false)}}
async function openJudgeWorkspace(){$("judgeIntro").hidden=true;$("judgeWorkspace").hidden=false;$("judgeName").textContent=judgeSession.user.name||"Pengadil";const identity=judgeSession.user.identityType==="ASING"?"PETUGAS ASING":`${judgeSession.user.schoolRole||"Warga Sekolah"}${judgeSession.user.house?` • Rumah ${judgeSession.user.house}`:""}`;$("judgeScope").textContent=`${identity} • ${judgeSession.user.judgeLabel||judgeSession.user.role||"Pengadil"} • Skop: ${judgeSession.user.judgeScope||"Semua acara"}`;await loadJudgeData()}
async function loadJudgeData(){try{judgeData=await judgeApi({action:"judgeData",token:judgeSession.token,year:$("judgeYear").value});renderJudgeWorkspace()}catch(error){if(/sesi/i.test(error.message)){logoutJudge();return}alert(error.message)}}
function renderJudgeWorkspace(){const events=judgeData.events||[],entries=judgeData.entries||[],results=judgeData.results||[];$("judgeEventCount").textContent=events.length;$("judgeEntryCount").textContent=entries.length;$("judgeResultCount").textContent=results.length;$("judgeEventGrid").innerHTML=events.length?events.map(event=>{const count=entries.filter(row=>row.eventId===event.id).length,done=results.filter(row=>row.eventId===event.id).length;return `<button type="button" data-judge-event="${safe(event.id)}"><small>${safe(event.discipline||"Acara")} • ${safe(event.cohort)} • ${safe(event.gender)}</small><b>${safe(event.name)}</b><span>${event.mode==="higher"?"📏 Ukuran tertinggi":"⏱ Masa terendah"}</span><em>${done}/${isRelay(event)?4:count} catatan tersedia</em></button>`}).join(""):'<div class="secure-empty">Tiada acara ditetapkan untuk kod akses ini.</div>';document.querySelectorAll("[data-judge-event]").forEach(button=>button.onclick=()=>openJudgeResult(button.dataset.judgeEvent));const filter=$("judgeResultFilter"),selected=filter.value;filter.innerHTML='<option value="">Semua acara</option>'+events.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.cohort)} • ${safe(event.gender)}</option>`).join("");filter.value=selected;renderJudgeResults()}
function renderJudgeResults(){const filter=$("judgeResultFilter").value,rows=(judgeData?.results||[]).filter(row=>!filter||row.eventId===filter);$("judgeResultRows").innerHTML=rows.length?'<div class="secure-row judge-result-row secure-head"><span>Ked.</span><span>Acara / peserta</span><span>Rumah</span><span>Catatan</span><span>Direkod oleh</span></div>'+rows.map(row=>`<div class="secure-row judge-result-row"><b class="place-badge place-${safe(row.place)}">${safe(row.place||"—")}</b><span><strong>${safe(row.event)}</strong><small>${safe(row.athlete||`Pasukan Rumah ${row.house}`)} • ${safe(row.category)}</small></span><span>${safe(row.house)}</span><b>${safe(row.mark||`${row.value} ${row.unit}`)}</b><small>${safe(row.recordedBy||"—")}</small></div>`).join(""):'<div class="secure-empty">Belum ada catatan rasmi untuk acara ini.</div>'}
function openJudgeResult(eventId=""){const events=judgeData?.events||[];$("judgeEvent").innerHTML='<option value="">Pilih acara</option>'+events.map(event=>`<option value="${safe(event.id)}">${safe(event.name)} • ${safe(event.cohort)} • ${safe(event.gender)}</option>`).join("");$("judgeEvent").value=eventId;$("judgeValue").value="";$("judgeResultMessage").textContent="";updateJudgeContestants();$("judgeResultDialog").showModal()}
function updateJudgeContestants(){const event=(judgeData?.events||[]).find(row=>row.id===$("judgeEvent").value),entries=(judgeData?.entries||[]).filter(row=>row.eventId===event?.id),relay=isRelay(event);if(!event){$("judgeContestant").innerHTML='<option value="">Pilih acara dahulu</option>';return}if(relay){const houses=[...new Set(entries.map(row=>row.house).filter(Boolean))];$("judgeContestant").innerHTML='<option value="">Pilih pasukan rumah</option>'+houses.map(house=>`<option value="${safe(house)}">Pasukan Rumah ${safe(house)}</option>`).join("")}else $("judgeContestant").innerHTML='<option value="">Pilih peserta</option>'+entries.map(row=>`<option value="${safe(row.pupilId)}">${safe(row.name)} • Rumah ${safe(row.house)}</option>`).join("");$("judgeUnit").value=event.unit||"saat";$("judgeUnit").disabled=true;$("judgeValueLabel").textContent=event.mode==="higher"?"Ukuran terbaik":"Masa larian";$("judgeGuidance").textContent=event.mode==="higher"?"Masukkan ukuran dalam meter. Nilai paling tinggi menerima kedudukan pertama.":"Masukkan masa dalam saat. Nilai paling rendah menerima kedudukan pertama."}
async function saveJudgeResult(event){event.preventDefault();const button=event.submitter,eventInfo=(judgeData?.events||[]).find(row=>row.id===$("judgeEvent").value),relay=isRelay(eventInfo);judgeBusy(button,true,"Menyimpan…");try{const result=await judgeApi({action:"saveResult",token:judgeSession.token,year:$("judgeYear").value,eventId:$("judgeEvent").value,athleteId:relay?"":$("judgeContestant").value,house:relay?$("judgeContestant").value:"",value:$("judgeValue").value,unit:$("judgeUnit").value});judgeMessage($("judgeResultMessage"),result.message,"success");await loadJudgeData();setTimeout(()=>$("judgeResultDialog").close(),650)}catch(error){judgeMessage($("judgeResultMessage"),error.message)}finally{judgeBusy(button,false)}}
function logoutJudge(){sessionStorage.removeItem(JUDGE_SESSION_KEY);location.reload()}
$("judgeLoginForm").addEventListener("submit",loginJudge);$("judgeIdentityType").addEventListener("change",updateJudgeIdentity);$("judgeIc").addEventListener("input",()=>$("judgeIc").value=$("judgeIc").value.replace(/\D/g,""));$("judgeYear").addEventListener("change",loadJudgeData);$("judgeLogout").addEventListener("click",logoutJudge);$("newJudgeResult").addEventListener("click",()=>openJudgeResult());$("judgeEvent").addEventListener("change",updateJudgeContestants);$("judgeResultFilter").addEventListener("change",renderJudgeResults);$("judgeResultForm").addEventListener("submit",saveJudgeResult);document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>button.closest("dialog").close());updateJudgeIdentity();try{judgeSession=JSON.parse(sessionStorage.getItem(JUDGE_SESSION_KEY)||"null")}catch{judgeSession=null}if(judgeSession?.token)openJudgeWorkspace();
